// Auto-extracted from missing-roadmap-steps.ts — p1, p2, p3 only
export const extraRoadmapSteps: import("~/lib/mock-data").RoadmapStep[] = [
  {
    id: "rs100",
    professionId: "p1",
    gradeLevelId: "g1",
    gradeName: "Pre-K",
    gradeShortCode: "prek",
    description: "Space exploration begins with wonder! At this age, nurture curiosity about the sky, moon, and stars. Read picture books about astronauts and planets. Imaginative play as a 'space explorer' builds the earliest dream of reaching the stars.",
    subjects: ["Early Science (Sky & Stars)","Counting & Numbers","Imaginative Play","Fine Motor Skills (Drawing)"],
    extracurriculars: [{"name":"NASA Space Place","url":"https://spaceplace.nasa.gov/","description":"Free NASA website with games, crafts, and activities about space designed for young children."},{"name":"Local Library Astronomy Storytime","url":"https://www.ala.org/","description":"Many public libraries host space-themed storytimes and early STEM programs for preschoolers."}],
    supplemental: [{"name":"Mousetronaut by Mark Kelly","url":"","type":"book"},{"name":"On the Launch Pad: A Counting Book About Rockets","url":"","type":"book"}],
  },
  {
    id: "rs101",
    professionId: "p1",
    gradeLevelId: "g3",
    gradeName: "1st Grade",
    gradeShortCode: "1",
    description: "Build foundational reading and math skills — astronauts need strong communication and quantitative abilities. Start a 'space journal' where you draw and write about what you learn. Visit a science museum to see real rockets or planetarium shows.",
    subjects: ["Reading & Phonics","Math (Addition & Subtraction)","Science Exploration","Handwriting & Writing"],
    extracurriculars: [{"name":"Smithsonian National Air and Space Museum — Kids","url":"https://airandspace.si.edu/","description":"Online exhibits and interactive activities about flight and space exploration."},{"name":"Make a Paper Rocket","url":"https://www.jpl.nasa.gov/edu/learn/project/make-a-straw-rocket/","description":"NASA JPL activity: build and launch a simple straw rocket while learning basic physics."}],
    supplemental: [{"name":"The Magic School Bus: Lost in the Solar System","url":"","type":"book"},{"name":"PBS Kids — Ready Jet Go!","url":"https://pbskids.org/readyjetgo/","type":"video"}],
  },
  {
    id: "rs102",
    professionId: "p1",
    gradeLevelId: "g4",
    gradeName: "2nd Grade",
    gradeShortCode: "2",
    description: "Deepen reading comprehension with space-themed non-fiction. Practice math facts — future astronauts use math constantly for calculations and navigation. Start learning about the solar system: planet names, order from the sun, and basic facts.",
    subjects: ["Reading Comprehension","Math (Place Value & Measurement)","Earth & Space Science","Art (Drawing Planets & Rockets)"],
    extracurriculars: [{"name":"Night Sky Observation","url":"https://www.nasa.gov/stem-content/star-finder/","description":"Use a star finder chart from NASA to identify constellations in the night sky with family."},{"name":"LEGO Space Sets","url":"https://www.lego.com/en-us/themes/space","description":"Build LEGO space models — develops spatial reasoning and engineering thinking through creative play."}],
    supplemental: [{"name":"National Geographic Kids: First Big Book of Space","url":"","type":"book"},{"name":"BrainPOP: Solar System","url":"https://www.brainpop.com/science/space/solarsystem/","type":"video"}],
  },
  {
    id: "rs103",
    professionId: "p1",
    gradeLevelId: "g5",
    gradeName: "3rd Grade",
    gradeShortCode: "3",
    description: "Transition from 'learning to read' to 'reading to learn' about space. Math skills expand — multiplication and division are used in real calculations for distance, speed, and time in space travel. Participate in a school science fair with a space-themed project.",
    subjects: ["Reading (Nonfiction Space Books)","Math (Multiplication & Division)","Science (Solar System & Gravity)","Geography (Earth from Space)"],
    extracurriculars: [{"name":"Girlstart / STEM Programs","url":"https://www.girlstart.org/","description":"After-school STEM programs with space science activities for elementary students."},{"name":"Local Planetarium Membership","url":"https://www.astc.org/","description":"Find a planetarium near you — regular visits build deep space knowledge through immersive shows."}],
    supplemental: [{"name":"DK Findout! Solar System","url":"https://www.dkfindout.com/us/space/solar-system/","type":"article"},{"name":"Who Was Neil Armstrong?","url":"","type":"book"}],
  },
  {
    id: "rs104",
    professionId: "p1",
    gradeLevelId: "g6",
    gradeName: "4th Grade",
    gradeShortCode: "4",
    description: "Develop research skills — assign a research project about an astronaut or space mission. Math now includes fractions and geometry, which astronauts use for orbital calculations. Start learning the scientific method through hands-on experiments.",
    subjects: ["English Language Arts (Research Writing)","Math (Fractions & Geometry)","Science (Scientific Method)","Social Studies (Space History)"],
    extracurriculars: [{"name":"Science Olympiad (Elementary)","url":"https://www.soinc.org/","description":"Compete in STEM events — astronomy, rocketry, and engineering challenges build teamwork and knowledge."},{"name":"4-H STEM Programs","url":"https://4-h.org/programs/stem/","description":"Hands-on STEM projects including rocketry, robotics, and aerospace exploration."}],
    supplemental: [{"name":"Endurance: A Year in Space — Young Readers Edition by Scott Kelly","url":"","type":"book"},{"name":"Mystery Science: Spaceship Earth","url":"https://mysteryscience.com/","type":"course"}],
  },
  {
    id: "rs105",
    professionId: "p1",
    gradeLevelId: "g8",
    gradeName: "6th Grade",
    gradeShortCode: "6",
    description: "Middle school brings deeper science and math. Take pre-algebra seriously — algebra is the language of physics and orbital mechanics. Join a robotics or rocketry club. Start tracking current space news: NASA missions, SpaceX launches, and ISS research.",
    subjects: ["Pre-Algebra","Earth & Space Science","English (Technical Reading)","Physical Education"],
    extracurriculars: [{"name":"Team America Rocketry Challenge (TARC)","url":"https://rocketcontest.org/","description":"Design, build, and launch model rockets — the world's largest student rocket contest (middle and high school)."},{"name":"Civil Air Patrol Cadet Program (Age 12+)","url":"https://www.gocivilairpatrol.com/programs/cadets","description":"Aerospace education, leadership training, and free orientation flights for youth 12 and older."}],
    supplemental: [{"name":"NASA's Eyes","url":"https://eyes.nasa.gov/","type":"program"},{"name":"Crash Course: Astronomy","url":"https://www.youtube.com/playlist?list=PL8dPuuaLjXtPAJr1ysd5yGIyiSFuh0mIL","type":"video"}],
  },
  {
    id: "rs106",
    professionId: "p1",
    gradeLevelId: "g9",
    gradeName: "7th Grade",
    gradeShortCode: "7",
    description: "Dive into physics concepts: motion, forces, and energy. Algebra skills become critical. Join a middle school STEM club or start one. Read astronaut autobiographies — they reveal the real paths people took to reach space. Physical fitness matters: start regular exercise routines.",
    subjects: ["Algebra Readiness","Physical Science (Physics Intro)","English (Biographies/Nonfiction)","Geography","Physical Education"],
    extracurriculars: [{"name":"Zero Robotics (Middle School)","url":"https://zerorobotics.mit.edu/","description":"Program SPHERES satellites on the International Space Station — write code that runs in space!"},{"name":"Astronomy Club / Middle School Science Club","url":"https://www.sciencebuddies.org/","description":"Start or join a science club — use Science Buddies for astronomy and physics project ideas."}],
    supplemental: [{"name":"Reaching for the Moon by Buzz Aldrin (Young Readers)","url":"","type":"book"},{"name":"Khan Academy: Forces and Newton's Laws","url":"https://www.khanacademy.org/science/physics/forces-newtons-laws","type":"course"}],
  },
  {
    id: "rs107",
    professionId: "p1",
    gradeLevelId: "g10",
    gradeName: "8th Grade",
    gradeShortCode: "8",
    description: "Take the most advanced math and science available — algebra and physical science are essential. Start learning about the engineering design process. NASA internships and programs become available at this age. Research what NASA looks for in astronaut candidates.",
    subjects: ["Algebra I","Physical Science","English (Technical Communication)","Computer Skills (Coding Intro)","PE / Fitness"],
    extracurriculars: [{"name":"NASA TechRise Student Challenge","url":"https://www.futureengineers.org/nasatechrise","description":"Design and build experiments for high-altitude balloons — tested in real flight conditions."},{"name":"FIRST Tech Challenge (FTC)","url":"https://www.firstinspires.org/robotics/ftc","description":"Build and program robots — develops engineering, programming, and teamwork skills essential for space missions."}],
    supplemental: [{"name":"The Right Stuff by Tom Wolfe","url":"","type":"book"},{"name":"NASA App","url":"https://www.nasa.gov/nasa-app/","type":"program"}],
  },
  {
    id: "rs108",
    professionId: "p1",
    gradeLevelId: "g11",
    gradeName: "9th Grade",
    gradeShortCode: "9",
    description: "Start building a strong STEM transcript. Take Honors Biology, Algebra II, and any available engineering electives. Physics is the astronaut's most critical science — sign up for it next year if possible. Join a competitive robotics or rocketry team. Begin learning a second language (NASA values multilingual crewmembers).",
    subjects: ["Honors Biology","Algebra II","English (Research Writing)","Foreign Language (Russian, Mandarin, or Japanese)","PE / Athletic Training"],
    extracurriculars: [{"name":"FIRST Robotics Competition (FRC)","url":"https://www.firstinspires.org/robotics/frc","description":"Design and build competition robots — many NASA astronauts started in FIRST programs."},{"name":"NASA High School Aerospace Scholars (HAS)","url":"https://www.nasa.gov/learning-resources/high-school-aerospace-scholars/","description":"Texas-based program (with national reach) — online coursework and on-site summer experience at NASA."}],
    supplemental: [{"name":"Carrying the Fire by Michael Collins","url":"","type":"book"},{"name":"edX: Introduction to Aerospace Engineering (TU Delft)","url":"https://www.edx.org/learn/aerospace-engineering","type":"course"}],
  },
  {
    id: "rs109",
    professionId: "p1",
    gradeLevelId: "g13",
    gradeName: "11th Grade",
    gradeShortCode: "11",
    description: "This is the most critical high school year for aspiring astronauts. Take AP Physics 1 and AP Calculus AB. Consider dual-enrollment in math or science at a local college. Pursue a leadership role in your robotics team or Civil Air Patrol squadron. Research colleges with strong aerospace engineering and NASA partnerships.",
    subjects: ["AP Physics 1","AP Calculus AB","AP Chemistry","Computer Science (AP or elective)","Leadership / Public Speaking"],
    extracurriculars: [{"name":"NASA OSTEM Internship (High School)","url":"https://www.nasa.gov/learning-resources/internship-programs/","description":"Paid high school internships at NASA centers — work alongside scientists and engineers on real projects."},{"name":"Congressional Award","url":"https://www.congressionalaward.org/","description":"Earn recognition for voluntary public service, personal development, physical fitness, and exploration."}],
    supplemental: [{"name":"How to Astronaut by Terry Virts","url":"","type":"book"},{"name":"Coursera: Spacecraft Dynamics & Control (University of Colorado)","url":"https://www.coursera.org/specializations/spacecraft-dynamics-control","type":"course"}],
  },
  {
    id: "rs110",
    professionId: "p1",
    gradeLevelId: "g14",
    gradeName: "12th Grade",
    gradeShortCode: "12",
    description: "Apply to universities with strong aerospace engineering programs and NASA funding. Complete AP Physics C and AP Calculus BC — these are direct equivalents to first-year college engineering courses. Continue physical fitness training (NASA astronaut physical is demanding). Consider a gap year or summer program in aviation or scuba diving.",
    subjects: ["AP Physics C (Mechanics & E&M)","AP Calculus BC","AP Computer Science A","Engineering Design / Capstone","AP English"],
    extracurriculars: [{"name":"NASA Community College Aerospace Scholars (NCAS)","url":"https://www.nasa.gov/learning-resources/community-college-aerospace-scholars/","description":"For graduating seniors — online course and potential on-site experience at a NASA center."},{"name":"Private Pilot Ground School","url":"https://www.aopa.org/training-and-safety/online-learning","description":"Start studying for a private pilot license — flight hours are a major asset for astronaut applications."}],
    supplemental: [{"name":"NASA Astronaut Candidate Application Guide","url":"https://www.nasa.gov/humans-in-space/astronauts/astronaut-candidate-program/","type":"article"},{"name":"SCUBA Certification (PADI)","url":"https://www.padi.com/","type":"program"}],
  },
  {
    id: "rs111",
    professionId: "p1",
    gradeLevelId: "g17",
    gradeName: "PhD / Doctoral",
    gradeShortCode: "phd",
    description: "A Ph.D. in aerospace engineering, physics, chemistry, biology, or geology strengthens an astronaut application significantly. NASA values deep expertise — many astronauts are Ph.D. scientists who have published research. Alternative path: M.D. + aerospace medicine fellowship. Continue building operational experience (flight ratings, expedition leadership, research in extreme environments).",
    subjects: ["Aerospace Engineering / Physics / Biology (Ph.D.)","Dissertation Research in Space-Relevant Topic","Advanced Orbital Mechanics","Spacecraft Systems Design","Publishing & Presenting Research"],
    extracurriculars: [{"name":"NASA Postdoctoral Program (NPP)","url":"https://www.nasa.gov/learning-resources/postdoctoral-program/","description":"Conduct cutting-edge research at NASA centers as a postdoctoral fellow — many astronauts come through this pathway."},{"name":"Analog Astronaut Missions (HI-SEAS, NEEMO)","url":"https://www.nasa.gov/mission/neemo/","description":"Participate in simulated space missions — underwater habitats and Mars analog stations that test crew resilience."}],
    supplemental: [{"name":"ESA Astronaut Selection Handbook","url":"https://www.esa.int/Science_Exploration/Human_and_Robotic_Exploration/Astronauts","type":"article"},{"name":"Journal of Spacecraft and Rockets (AIAA)","url":"https://arc.aiaa.org/journal/jsr","type":"article"}],
  },
  {
    id: "rs112",
    professionId: "p2",
    gradeLevelId: "g1",
    gradeName: "Pre-K",
    gradeShortCode: "prek",
    description: "The foundations of software engineering start with logical thinking and sequencing. Sorting games, pattern recognition, and simple 'if-then' logic are the earliest forms of computational thinking. Building with blocks and solving puzzles develop the problem-solving mindset that every coder needs.",
    subjects: ["Shapes & Patterns","Sequencing & Sorting","Counting","Creative Play (Building)"],
    extracurriculars: [{"name":"Code.org — Pre-Reader Express","url":"https://code.org/student/pre-reader-express","description":"Free introductory coding puzzles for children who haven't learned to read yet — drag-and-drop blocks teach sequencing."},{"name":"PBS Kids — Patterns and Sorting Games","url":"https://pbskids.org/games/logic/","description":"Free games that build pattern recognition and logical sequencing — the foundations of algorithmic thinking."}],
    supplemental: [{"name":"DK My First Coding Book","url":"","type":"book"}],
  },
  {
    id: "rs113",
    professionId: "p2",
    gradeLevelId: "g3",
    gradeName: "1st Grade",
    gradeShortCode: "1",
    description: "Build strong reading and math foundations — coding is built on literacy and numeracy. Participate in 'Hour of Code' activities (no reading required for early levels). Pattern recognition games strengthen the brain's ability to think systematically.",
    subjects: ["Reading & Phonics","Math (Addition & Subtraction [basic])","Pattern Recognition","Handwriting"],
    extracurriculars: [{"name":"ScratchJr","url":"https://www.scratchjr.org/","description":"Free app where children program interactive stories and games using visual blocks — no reading required."},{"name":"Code.org — Course A","url":"https://code.org/student/elementary","description":"Free introductory coding course with drag-and-drop puzzles for early readers."}],
    supplemental: [{"name":"How to Code a Sandcastle by Josh Funk","url":"","type":"book"},{"name":"ScratchJr Learn Website","url":"https://www.scratchjr.org/learn","type":"video"}],
  },
  {
    id: "rs114",
    professionId: "p2",
    gradeLevelId: "g4",
    gradeName: "2nd Grade",
    gradeShortCode: "2",
    description: "Reading comprehension is key for understanding coding instructions and documentation. Practice math facts — software engineering depends on mathematical thinking. Try coding with block-based platforms that don't require typing. Create simple animations or games.",
    subjects: ["Reading Comprehension","Math (Place Value & Measurement)","Science Inquiry","Keyboarding (Intro)"],
    extracurriculars: [{"name":"Scratch (MIT)","url":"https://scratch.mit.edu/","description":"Create stories, games, and animations with visual block programming — used by millions of kids worldwide."},{"name":"CS Unplugged","url":"https://www.csunplugged.org/","description":"Learn computer science concepts without computers — using cards, string, and physical activities."}],
    supplemental: [{"name":"DK Workbooks: Coding with Scratch","url":"","type":"book"},{"name":"Code.org — Course B","url":"https://code.org/student/elementary","type":"course"}],
  },
  {
    id: "rs115",
    professionId: "p2",
    gradeLevelId: "g5",
    gradeName: "3rd Grade",
    gradeShortCode: "3",
    description: "Transition to more complex logical thinking. Practice multiplication and division — these operations are fundamental to all programming. Start using Scratch to build multi-level games with variables. Join a coding club if available at school or the library.",
    subjects: ["Reading (Nonfiction / Instructions)","Math (Multiplication & Division)","Science (Experiments & Logic)","Computer Literacy"],
    extracurriculars: [{"name":"Code.org — Course D","url":"https://code.org/student/elementary","description":"Continue coding with loops, conditionals, and events — building toward real programming concepts."},{"name":"CoderDojo","url":"https://coderdojo.com/","description":"Free, volunteer-led coding clubs for kids 7-17 — find a local Dojo or start one."}],
    supplemental: [{"name":"Secret Coders by Gene Luen Yang","url":"","type":"book"},{"name":"Tynker","url":"https://www.tynker.com/","type":"program"}],
  },
  {
    id: "rs116",
    professionId: "p2",
    gradeLevelId: "g6",
    gradeName: "4th Grade",
    gradeShortCode: "4",
    description: "Expand coding skills with more complex Scratch projects that use variables and custom blocks. Math now includes fractions and geometry — both essential for game development and graphics programming. Work on typing skills — efficient keyboarding makes coding much faster.",
    subjects: ["English Language Arts","Math (Fractions & Geometry)","Science (Logical Reasoning)","Keyboarding Skills"],
    extracurriculars: [{"name":"Code.org — Course F","url":"https://code.org/student/elementary","description":"The final elementary course — introduces variables, functions, and deeper programming concepts."},{"name":"Girls Who Code (Elementary)","url":"https://girlswhocode.com/","description":"Coding clubs for girls 3rd-5th grade — building confidence and community in tech."}],
    supplemental: [{"name":"Super Scratch Programming Adventure!","url":"","type":"book"},{"name":"CodeCombat","url":"https://codecombat.com/","type":"program"}],
  },
  {
    id: "rs117",
    professionId: "p2",
    gradeLevelId: "g7",
    gradeName: "5th Grade",
    gradeShortCode: "5",
    description: "This is the ideal age to transition from block coding to text-based programming. Start learning Python — the most beginner-friendly text language. Math pre-algebra skills are critical. Join or start a coding club and participate in an Hour of Code event. Build a simple text-based game or calculator.",
    subjects: ["Math (Pre-Algebra)","General Science","Computer Science (Python Intro)","English (Technical Reading)"],
    extracurriculars: [{"name":"CS First (Google)","url":"https://csfirst.withgoogle.com/","description":"Free coding curriculum using Scratch with themed projects like storytelling, sports, and game design."},{"name":"FIRST LEGO League","url":"https://www.firstlegoleague.org/","description":"Build and program LEGO robots to solve challenges — team-based engineering and coding."}],
    supplemental: [{"name":"Python for Kids by Jason R. Briggs","url":"","type":"book"},{"name":"Raspberry Pi Foundation — Projects","url":"https://projects.raspberrypi.org/","type":"program"}],
  },
  {
    id: "rs118",
    professionId: "p2",
    gradeLevelId: "g8",
    gradeName: "6th Grade",
    gradeShortCode: "6",
    description: "Start learning Python or JavaScript in earnest. Practice solving math problems with code — write simple programs that perform calculations. Explore web development: learn HTML and CSS to build your first personal webpage. Join an online coding community for young learners.",
    subjects: ["Pre-Algebra / Algebra Readiness","Earth Science / Physics Intro","Computer Science (Python/HTML)","English (Documentation Writing)"],
    extracurriculars: [{"name":"Khan Academy — Computer Programming","url":"https://www.khanacademy.org/computing/computer-programming","description":"Free courses in JavaScript, HTML/CSS, and SQL with interactive coding environments."},{"name":"Codecademy (Free Tier)","url":"https://www.codecademy.com/","description":"Interactive coding courses — start with Python or Web Development tracks."}],
    supplemental: [{"name":"How to Code: A Step-by-Step Guide to Computer Coding (Max Wainewright)","url":"","type":"book"},{"name":"replit — Online Code Editor","url":"https://replit.com/","type":"program"}],
  },
  {
    id: "rs119",
    professionId: "p2",
    gradeLevelId: "g9",
    gradeName: "7th Grade",
    gradeShortCode: "7",
    description: "Take algebra seriously — it's the mathematical foundation of all programming logic. Write Python programs that solve real problems you care about. Start a GitHub account to store and share your code. Contribute to simple open-source projects (documentation fixes are a great start).",
    subjects: ["Algebra I","Computer Science Elective","English (Technical Writing)","Science (Data & Graphing)"],
    extracurriculars: [{"name":"Hack Club","url":"https://hackclub.com/","description":"Global network of high school coding clubs with hackathons and workshops — join or start one at your school."},{"name":"MIT App Inventor","url":"https://appinventor.mit.edu/","description":"Build fully functional Android apps with a visual drag-and-drop programming environment."}],
    supplemental: [{"name":"Automate the Boring Stuff with Python — Al Sweigart","url":"https://automatetheboringstuff.com/","type":"book"},{"name":"freeCodeCamp","url":"https://www.freecodecamp.org/","type":"course"}],
  },
  {
    id: "rs120",
    professionId: "p2",
    gradeLevelId: "g10",
    gradeName: "8th Grade",
    gradeShortCode: "8",
    description: "Take the most advanced math available — algebra and geometry are essential. If your school offers a computer science elective, take it. Build a portfolio project: a personal website, a simple game, or a tool that solves a problem for your community. Start preparing for AP Computer Science next year.",
    subjects: ["Algebra I / Geometry","Physical Science","Computer Science / Programming Elective","English (Documentation & Communication)"],
    extracurriculars: [{"name":"CS50x — Harvard's Intro to Computer Science","url":"https://cs50.harvard.edu/x/","description":"Harvard's legendary intro CS course, free online — the best starting point for serious programming students."},{"name":"Google Code Next","url":"https://codenext.withgoogle.com/","description":"Free computer science education program for high school students — in-person labs in select cities."}],
    supplemental: [{"name":"The Self-Taught Programmer by Cory Althoff","url":"","type":"book"},{"name":"LeetCode (Easy Problems)","url":"https://leetcode.com/","type":"program"}],
  },
  {
    id: "rs121",
    professionId: "p2",
    gradeLevelId: "g12",
    gradeName: "10th Grade",
    gradeShortCode: "10",
    description: "Take AP Computer Science A (Java) or AP Computer Science Principles. Deepen Python skills — build data-focused projects. Start learning about data structures (arrays, lists, dictionaries). Participate in a hackathon. Contribute to open-source projects on GitHub.",
    subjects: ["AP Computer Science A / Principles","Geometry / Algebra II","AP Statistics (useful for data)","English (Technical Writing)"],
    extracurriculars: [{"name":"Congressional App Challenge","url":"https://www.congressionalappchallenge.us/","description":"Official House of Representatives competition — build and submit an original app to represent your district."},{"name":"Major League Hacking (High School)","url":"https://mlh.io/","description":"Student hackathon league — many events welcome high school participants alongside college students."}],
    supplemental: [{"name":"Cracking the Coding Interview — Gayle Laakmann McDowell","url":"","type":"book"},{"name":"The Odin Project","url":"https://www.theodinproject.com/","type":"course"}],
  },
  {
    id: "rs122",
    professionId: "p2",
    gradeLevelId: "g13",
    gradeName: "11th Grade",
    gradeShortCode: "11",
    description: "Take AP Computer Science A and AP Calculus. Master data structures: arrays, linked lists, stacks, queues, trees. Build a substantial project — a web app, mobile app, or game. Research computer science programs at top universities. Look into summer coding programs like Google CSSI or Microsoft Discovery Program.",
    subjects: ["AP Computer Science A","AP Calculus AB","AP Physics","English (Communication)","Web/Mobile Development (self-study)"],
    extracurriculars: [{"name":"Google Computer Science Summer Institute (CSSI)","url":"https://buildyourfuture.withgoogle.com/programs/computer-science-summer-institute","description":"Free four-week summer program for graduating high school seniors interested in computing."},{"name":"USACO (USA Computing Olympiad)","url":"https://usaco.org/","description":"Competitive programming competition — develops algorithmic problem-solving skills at the highest level."}],
    supplemental: [{"name":"Grokking Algorithms — Aditya Bhargava","url":"","type":"book"},{"name":"Coursera: Algorithms Specialization (Stanford)","url":"https://www.coursera.org/specializations/algorithms","type":"course"}],
  },
  {
    id: "rs123",
    professionId: "p2",
    gradeLevelId: "g14",
    gradeName: "12th Grade",
    gradeShortCode: "12",
    description: "Take AP Calculus BC and AP Computer Science A (if not already taken). Apply to top CS and engineering programs. Build your capstone project: a full-stack web application that solves a real problem. Continue contributing to open-source. Prepare for technical college interviews.",
    subjects: ["AP Calculus BC","AP Computer Science A (if available)","AP Statistics","Economics / Entrepreneurship Elective","English (College Essays)"],
    extracurriculars: [{"name":"NCWIT Aspirations in Computing","url":"https://www.aspirations.org/","description":"National recognition and community for students who identify as women, genderqueer, or non-binary in computing."},{"name":"Build a Portfolio on GitHub Pages","url":"https://pages.github.com/","description":"Host a free portfolio website using GitHub Pages to showcase your coding projects for college applications."}],
    supplemental: [{"name":"MIT OpenCourseWare: 6.006 Introduction to Algorithms","url":"https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/","type":"course"},{"name":"Code: The Hidden Language of Computer Hardware and Software — Charles Petzold","url":"","type":"book"}],
  },
  {
    id: "rs124",
    professionId: "p2",
    gradeLevelId: "g16",
    gradeName: "Graduate",
    gradeShortCode: "grad",
    description: "Pursue a Master's in Computer Science, Software Engineering, or a specialized field (AI/ML, cybersecurity, distributed systems). Deepen expertise through research or industry internships. Many top tech companies value advanced degrees for specialized roles. Build a professional network at conferences.",
    subjects: ["Advanced Algorithms","Machine Learning / AI","Distributed Systems","Software Architecture","Thesis / Capstone Project"],
    extracurriculars: [{"name":"Google PhD Fellowship","url":"https://research.google/outreach/phd-fellowship/","description":"Fellowship program supporting graduate students in computer science and related fields."},{"name":"ACM Student Chapter (Graduate)","url":"https://www.acm.org/","description":"Professional organization for computing — conferences, publications, and career resources."}],
    supplemental: [{"name":"Designing Data-Intensive Applications — Martin Kleppmann","url":"","type":"book"},{"name":"Papers with Code","url":"https://paperswithcode.com/","type":"article"}],
  },
  {
    id: "rs125",
    professionId: "p2",
    gradeLevelId: "g17",
    gradeName: "PhD / Doctoral",
    gradeShortCode: "phd",
    description: "A Ph.D. in Computer Science opens doors to cutting-edge research at top tech companies, national labs, and academia. Specialize in AI/ML, systems, security, programming languages, or human-computer interaction. Publish at top conferences (NeurIPS, ICML, SOSP, PLDI, CHI). Develop deep expertise that can launch a research career or CTO-level industry roles.",
    subjects: ["Computer Science Ph.D. (Specialized Field)","Dissertation Research","Teaching / TA Experience","Conference Publications","Grant Writing"],
    extracurriculars: [{"name":"NSF Graduate Research Fellowship","url":"https://www.nsfgrfp.org/","description":"Prestigious fellowship providing three years of funding for graduate research in STEM fields."},{"name":"Research Internships (Google Brain, Meta AI, Microsoft Research)","url":"https://research.google/careers/","description":"Paid Ph.D. research internships at top industry labs — often lead to full-time research scientist positions."}],
    supplemental: [{"name":"arXiv — CS Research Papers","url":"https://arxiv.org/list/cs/recent","type":"article"},{"name":"The Ph.D. Grind — Philip Guo","url":"","type":"book"}],
  },
  {
    id: "rs126",
    professionId: "p3",
    gradeLevelId: "g1",
    gradeName: "Pre-K",
    gradeShortCode: "prek",
    description: "Nurture empathy and curiosity about the human body. Play 'doctor' with stuffed animals and learn body part names. Read books about going to the doctor to build comfort with medical settings. Early interest in helping others is the seed of a future physician.",
    subjects: ["Body Awareness & Health","Counting & Sorting","Social-Emotional Skills","Fine Motor Skills"],
    extracurriculars: [{"name":"Sesame Street — Health and Wellness","url":"https://sesamestreet.org/","description":"Videos and activities about doctor visits, bodies, and healthy habits."},{"name":"Children's Museum Health Exhibits","url":"https://www.childrensmuseums.org/","description":"Many children's museums have doctor/nurse role-play areas for early healthcare exposure."}],
    supplemental: [{"name":"Corduroy Goes to the Doctor","url":"","type":"book"},{"name":"The Berenstain Bears Go to the Doctor","url":"","type":"book"}],
  },
  {
    id: "rs127",
    professionId: "p3",
    gradeLevelId: "g2",
    gradeName: "Kindergarten",
    gradeShortCode: "k",
    description: "Build curiosity about how the body works. Learn the five senses, basic hygiene, and healthy eating. Drawing the human body and naming parts reinforces early anatomy knowledge. Practice counting heartbeats and measuring things — early clinical skills disguised as play.",
    subjects: ["Early Science (Body & Senses)","Counting & Measuring","Drawing & Fine Motor Skills","Social-Emotional Learning"],
    extracurriculars: [{"name":"PBS Kids — Sid the Science Kid: Health Episodes","url":"https://pbskids.org/sid/health","description":"Sid explores how the body works — digestion, germs, exercise, and more for kindergarteners."},{"name":"Local Children's Hospital Tours","url":"","description":"Many pediatric hospitals offer 'teddy bear clinics' or child-friendly tours to reduce medical anxiety."}],
    supplemental: [{"name":"Inside Your Outside (Cat in the Hat's Learning Library)","url":"","type":"book"},{"name":"The Magic School Bus: Inside the Human Body","url":"","type":"book"}],
  },
  {
    id: "rs128",
    professionId: "p3",
    gradeLevelId: "g3",
    gradeName: "1st Grade",
    gradeShortCode: "1",
    description: "Strengthen reading and math — doctors read constantly (charts, journals, research) and use math for dosages and measurements. Learn basic first aid: washing cuts, using bandages. Pay attention to how your own body works and heals. Observe how doctors and nurses help people feel better.",
    subjects: ["Reading & Phonics","Math (Addition & Subtraction)","Science (Living Things)","Health & Hygiene"],
    extracurriculars: [{"name":"American Red Cross — First Aid for Kids","url":"https://www.redcross.org/","description":"Age-appropriate first aid information and activities for elementary students."},{"name":"KidsHealth.org","url":"https://kidshealth.org/","description":"Free website explaining how the body works, illnesses, and staying healthy — all in kid-friendly language."}],
    supplemental: [{"name":"A Day with a Doctor (Welcome Books)","url":"","type":"book"},{"name":"BrainPOP Jr.: Going to the Doctor","url":"https://jr.brainpop.com/health/bodies/goingtothedoctor/","type":"video"}],
  },
  {
    id: "rs129",
    professionId: "p3",
    gradeLevelId: "g4",
    gradeName: "2nd Grade",
    gradeShortCode: "2",
    description: "Deepen reading comprehension with non-fiction books about the human body. Introduce detailed anatomy: organs, bones, muscles. Practice careful observation — describe what you see in detail (a skill doctors use every day). Learn about germs and how the immune system protects us.",
    subjects: ["Reading Comprehension","Math (Measurement & Time)","Health Science","Art (Drawing the Body)"],
    extracurriculars: [{"name":"National Geographic Kids: Human Body","url":"https://kids.nationalgeographic.com/science/article/your-amazing-human-body","description":"Interactive articles about the brain, heart, digestion, and bones."},{"name":"Science Fair — Human Body Project","url":"","description":"Enter a school science fair with a project about heart rate, lung capacity, or hand washing effectiveness."}],
    supplemental: [{"name":"DK Eyewitness: Human Body","url":"","type":"book"},{"name":"BrainPOP: Human Body","url":"https://www.brainpop.com/health/bodysystems/","type":"video"}],
  },
  {
    id: "rs130",
    professionId: "p3",
    gradeLevelId: "g5",
    gradeName: "3rd Grade",
    gradeShortCode: "3",
    description: "Focus on biology foundations: cells, tissues, organs, body systems. Math skills (multiplication, division, fractions) are essential for calculating medication dosages. Start learning about nutrition and how food affects the body. Observe how medical professionals communicate with patients.",
    subjects: ["Life Science (Body Systems)","Math (Fractions & Decimals)","Reading (Nonfiction Science)","Health Education"],
    extracurriculars: [{"name":"Future Doctors (Elementary STEM)","url":"","description":"Look for local science or health summer camps focused on the human body and medicine for elementary students."},{"name":"4-H Healthy Living Programs","url":"https://4-h.org/programs/healthy-living/","description":"Youth programs covering nutrition, first aid, and understanding how the body stays healthy."}],
    supplemental: [{"name":"The Way We Work by David Macaulay","url":"","type":"book"},{"name":"Operation Ouch! (BBC / YouTube)","url":"https://www.youtube.com/user/operationouch","type":"video"}],
  },
  {
    id: "rs131",
    professionId: "p3",
    gradeLevelId: "g6",
    gradeName: "4th Grade",
    gradeShortCode: "4",
    description: "Expand biology knowledge: learn about genetics basics, how diseases spread, and how medicines work. Strengthen math foundations — future doctors need solid quantitative skills. Research different medical specialties: pediatrician, surgeon, cardiologist, neurologist. Read biographies of pioneering doctors.",
    subjects: ["English (Research Writing)","Math (Geometry & Proportions)","Life Science (Genetics & Disease)","Social Studies (Medical History)"],
    extracurriculars: [{"name":"Science Olympiad — Anatomy & Physiology","url":"https://www.soinc.org/","description":"Competitive event covering body systems — great preparation for future pre-med study."},{"name":"HOSA Future Health Professionals (Elementary)","url":"https://hosa.org/","description":"Some regions offer elementary health science exploration programs through HOSA partnerships."}],
    supplemental: [{"name":"Breakthrough! How Three People Saved Blue Babies and Changed Medicine Forever by Jim Murphy","url":"","type":"book"},{"name":"Mystery Science: Human Machine","url":"https://mysteryscience.com/","type":"course"}],
  },
  {
    id: "rs132",
    professionId: "p3",
    gradeLevelId: "g7",
    gradeName: "5th Grade",
    gradeShortCode: "5",
    description: "Build a strong foundation in biology and math. Learn the major body systems in detail: circulatory, respiratory, digestive, nervous, skeletal, and muscular. Begin developing study habits for science — medicine requires lifelong learning. Volunteer or participate in community health events.",
    subjects: ["Math (Pre-Algebra)","Life Science (Human Biology)","Health & Nutrition","English (Science Communication)"],
    extracurriculars: [{"name":"American Red Cross Babysitting Course (Age 11+)","url":"https://www.redcross.org/take-a-class/babysitting","description":"Learn first aid, CPR basics, and how to respond to emergencies — early healthcare skills."},{"name":"Local Hospital Junior Volunteer (some accept 12+)","url":"","description":"Some hospitals offer junior volunteer programs starting at age 12 — check local hospital requirements."}],
    supplemental: [{"name":"DK Human Body: A Visual Encyclopedia","url":"","type":"book"},{"name":"Khan Academy: Health and Medicine","url":"https://www.khanacademy.org/science/health-and-medicine","type":"course"}],
  },
  {
    id: "rs133",
    professionId: "p3",
    gradeLevelId: "g8",
    gradeName: "6th Grade",
    gradeShortCode: "6",
    description: "Take the most advanced science available — pre-algebra, life science, and any health electives. Start learning medical terminology roots (Greek and Latin prefixes/suffixes). Pay close attention to biology units on cells and microorganisms. Read about what doctors actually do day-to-day.",
    subjects: ["Pre-Algebra","Life Science (Advanced)","English (Medical Terminology)","Health Elective"],
    extracurriculars: [{"name":"HOSA — Future Health Professionals (Middle School)","url":"https://hosa.org/","description":"Start a HOSA chapter or join health science competitions — medical terminology, health education events."},{"name":"Teen Medical Academy (Local Hospitals)","url":"","description":"Many hospitals run summer academies introducing middle schoolers to medical careers — inquire at local hospitals."}],
    supplemental: [{"name":"Crash Course: Anatomy & Physiology","url":"https://www.youtube.com/playlist?list=PL8dPuuaLjXtOAKed_MxxWBNaPno5h3Zs8","type":"video"},{"name":"When Breath Becomes Air — Paul Kalanithi","url":"","type":"book"}],
  },
  {
    id: "rs134",
    professionId: "p3",
    gradeLevelId: "g9",
    gradeName: "7th Grade",
    gradeShortCode: "7",
    description: "Take algebra and the most advanced life science available. Begin learning human anatomy and physiology basics. Consider learning a second language — doctors who are bilingual can serve more patients. Start volunteering at a hospital, nursing home, or community clinic if age eligible.",
    subjects: ["Algebra I","Life Science / Biology","Foreign Language","English (Scientific Writing)"],
    extracurriculars: [{"name":"Medical Explorers Post","url":"https://www.exploring.org/medical/","description":"Hands-on career exploration with hospital rotations, mentorship, and clinical shadowing for ages 14+."},{"name":"Khan Academy: Human Biology","url":"https://www.khanacademy.org/science/biology","description":"Free biology courses covering cell biology, genetics, and human body systems."}],
    supplemental: [{"name":"The Emperor of All Maladies — Siddhartha Mukherjee","url":"","type":"book"},{"name":"TED-Ed: Health & Medicine","url":"https://ed.ted.com/lessons?category=health","type":"video"}],
  },
  {
    id: "rs135",
    professionId: "p3",
    gradeLevelId: "g10",
    gradeName: "8th Grade",
    gradeShortCode: "8",
    description: "Take biology at the highest level available. Learn the scientific method rigorously — doctors must understand research to practice evidence-based medicine. Start learning about the medical school pathway: pre-med major, MCAT, applications. Shadow a doctor if possible through family connections or programs.",
    subjects: ["Honors Biology","Geometry / Algebra II","Chemistry (Intro)","English (Research Writing)","Health / Psychology Elective"],
    extracurriculars: [{"name":"Stanford Medical Youth Science Program (SMYSP)","url":"https://med.stanford.edu/center-for-health-equity/education/youth-programs.html","description":"Summer program for low-income and underrepresented high school students interested in medicine."},{"name":"CDC Museum Disease Detective Camp","url":"https://www.cdc.gov/museum/","description":"Competitive summer camp at CDC headquarters in Atlanta — learn epidemiology and public health investigation."}],
    supplemental: [{"name":"AAMC — Aspiring Docs","url":"https://www.aamc.org/careers-in-medicine/aspiring-docs","type":"article"},{"name":"The Man Who Mistook His Wife for a Hat — Oliver Sacks","url":"","type":"book"}],
  },
  {
    id: "rs136",
    professionId: "p3",
    gradeLevelId: "g12",
    gradeName: "10th Grade",
    gradeShortCode: "10",
    description: "Take Honors Chemistry and AP Biology if available. Strengthen math through Algebra II or Pre-Calculus. Begin researching pre-med undergraduate programs. Look for summer medical programs at universities. Continue hospital volunteering and shadowing across different specialties.",
    subjects: ["AP Biology / Honors Chemistry","Algebra II / Pre-Calculus","English (Reading Medical Literature)","Foreign Language","Psychology"],
    extracurriculars: [{"name":"NIH High School Summer Internship Program (HS-SIP)","url":"https://www.training.nih.gov/programs/hs-sip","description":"Paid summer research internship at the National Institutes of Health for 11th and 12th graders."},{"name":"HOSA Competitive Events","url":"https://hosa.org/","description":"Compete in biomedical debate, medical innovation, clinical specialty events at HOSA conferences."}],
    supplemental: [{"name":"Being Mortal — Atul Gawande","url":"","type":"book"},{"name":"Khan Academy: AP Biology","url":"https://www.khanacademy.org/science/ap-biology","type":"course"}],
  },
  {
    id: "rs137",
    professionId: "p3",
    gradeLevelId: "g13",
    gradeName: "11th Grade",
    gradeShortCode: "11",
    description: "The most critical year for pre-med preparation. Take AP Biology, AP Chemistry, and AP Calculus. Pursue leadership roles in HOSA or other health organizations. Shadow doctors across at least 3 specialties (primary care, surgery, and a specialty of interest). Research direct medical programs (BS/MD).",
    subjects: ["AP Biology","AP Chemistry","AP Calculus AB","AP English Language","Psychology / Sociology"],
    extracurriculars: [{"name":"Research Science Institute (RSI) — MIT","url":"https://www.cee.org/programs/research-science-institute","description":"Highly selective summer research program — conduct original biomedical research with MIT mentors."},{"name":"Perry Initiative — Virtual Programs","url":"https://perryinitiative.org/","description":"Programs inspiring young women to pursue careers in orthopedic surgery and biomedical engineering."}],
    supplemental: [{"name":"MCAT Behavioral Sciences Review (Preview)","url":"https://www.aamc.org/students/prepare-mcat","type":"program"},{"name":"The House of God — Samuel Shem","url":"","type":"book"}],
  },
  {
    id: "rs138",
    professionId: "p3",
    gradeLevelId: "g14",
    gradeName: "12th Grade",
    gradeShortCode: "12",
    description: "Apply to universities with strong pre-med advising programs. Complete AP Biology, AP Chemistry, and AP Calculus exams for college credit. Continue shadowing and volunteering — aim for 100+ clinical hours. Start preparing for the adjustment to college-level science coursework. Consider gap year programs in global health or medical research.",
    subjects: ["AP Biology (Exam)","AP Chemistry (Exam)","AP Calculus BC","AP Psychology","Anatomy & Physiology Elective"],
    extracurriculars: [{"name":"Global Health Corps Fellowship","url":"https://ghcorps.org/","description":"Paid fellowship for graduating seniors interested in global health equity — gap year or post-college."},{"name":"Apply to BS/MD Combined Programs","url":"","description":"Research and apply to accelerated medical programs that combine undergrad and med school in 6-8 years."}],
    supplemental: [{"name":"The White Coat Investor — James Dahle (Student Edition)","url":"","type":"book"},{"name":"AAMC — Medical School Admission Requirements (MSAR)","url":"https://students-residents.aamc.org/medical-school-admission-requirements","type":"article"}],
  },
  {
    id: "rs139",
    professionId: "p3",
    gradeLevelId: "g17",
    gradeName: "PhD / Doctoral",
    gradeShortCode: "phd",
    description: "After medical school and residency, some physicians pursue an additional Ph.D. (M.D./Ph.D. dual-degree programs) or a research-focused fellowship. Medical scientists conduct translational research — turning lab discoveries into patient treatments. Alternatively, an M.D. alone qualifies for clinical research leadership roles. Academic medicine combines patient care, teaching, and research.",
    subjects: ["Clinical Research Methods","Advanced Biostatistics","Grant Writing","Teaching & Mentoring","Subspecialty Board Certification"],
    extracurriculars: [{"name":"NIH Loan Repayment Programs","url":"https://www.lrp.nih.gov/","description":"Pays up to $50,000/year of student loans for physicians conducting research at NIH or academic centers."},{"name":"AAMC Research on Care Community","url":"https://www.aamc.org/","description":"Network for physician-scientists advancing medical research and evidence-based practice."}],
    supplemental: [{"name":"New England Journal of Medicine","url":"https://www.nejm.org/","type":"article"},{"name":"JAMA — Journal of the American Medical Association","url":"https://jamanetwork.com/journals/jama","type":"article"}],
  },
];
