// p11 Data Scientist missing steps + p14 Civil Engineer + p15 Psychologist + p16 Electrician
import type { RoadmapStep } from "~/lib/mock-data";

export const missingRoadmapSteps: RoadmapStep[] = [
  // ═══════════════════════════════════════════════════════════════
  // p11 — Data Scientist (missing: g1,g3,g4,g5,g6,g8,g9,g10,g12,g13,g16,g17)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "rs600",
    professionId: "p11",
    gradeLevelId: "g1",
    gradeName: "Pre-K",
    gradeShortCode: "prek",
    description: "Data science starts with noticing patterns! At this age, children naturally sort, count, and ask 'why?' — the earliest forms of data analysis. Encourage sorting toys by color and size, counting everything, and asking questions about the world. Curiosity is the foundation of every great data scientist.",
    subjects: ["Sorting & Patterns", "Counting & Numbers", "Asking Questions", "Colors & Shapes"],
    extracurriculars: [
      { name: "Sesame Street — Counting & Patterns", url: "https://sesamestreet.org/", description: "Free videos and games teaching counting, sorting, and pattern recognition — foundational data thinking." },
      { name: "PBS Kids — Odd Squad", url: "https://pbskids.org/oddsquad/", description: "Math-based show where kid agents solve problems using data, patterns, and logic." },
    ],
    supplemental: [
      { name: "Countablock by Christopher Franceschelli", url: "", type: "book" },
      { name: "Press Here by Hervé Tullet", url: "", type: "book" },
    ],
  },
  {
    id: "rs601",
    professionId: "p11",
    gradeLevelId: "g3",
    gradeName: "1st Grade",
    gradeShortCode: "1",
    description: "Strengthen math and observation skills — data scientists need both. Practice counting, measuring, and recording information. Start a 'data journal' where you write down things you observe: weather each day, how many birds at the feeder, or your family's favorite foods. These are your first datasets!",
    subjects: ["Reading & Writing", "Math (Addition & Subtraction)", "Science (Observing & Recording)", "Art (Drawing Charts)"],
    extracurriculars: [
      { name: "Code.org — Course A", url: "https://code.org/student/elementary", description: "Free introductory coding puzzles that build computational thinking without needing to read." },
      { name: "PBS Kids — Cyberchase", url: "https://pbskids.org/cyberchase/", description: "Animated show where kids use math and data to solve problems — perfect for budding data thinkers." },
    ],
    supplemental: [
      { name: "The Great Graph Contest by Loreen Leedy", url: "", type: "book" },
      { name: "Starfall Math", url: "https://www.starfall.com/", type: "program" },
    ],
  },
  {
    id: "rs602",
    professionId: "p11",
    gradeLevelId: "g4",
    gradeName: "2nd Grade",
    gradeShortCode: "2",
    description: "Deepen math and data collection skills. Start making simple bar graphs and pictographs from data you collect — favorite snacks, daily temperatures, or types of cars that pass your street. Data scientists turn observations into visual stories. Practice measuring everything with rulers and scales.",
    subjects: ["Math (Measurement & Graphing)", "Reading Comprehension", "Science (Data Collection)", "Computer Skills (Intro)"],
    extracurriculars: [
      { name: "ScratchJr", url: "https://www.scratchjr.org/", description: "Create interactive stories while learning sequencing, counting, and logic — pre-coding for young data analysts." },
      { name: "National Geographic Kids — Weird But True", url: "https://kids.nationalgeographic.com/weird-but-true/", description: "Fun facts backed by data — learn to love interesting numbers and surprising statistics." },
    ],
    supplemental: [
      { name: "How to Be a Math Genius (DK)", url: "", type: "book" },
      { name: "BrainPOP Jr.: Tally Charts & Bar Graphs", url: "https://jr.brainpop.com/math/data/", type: "video" },
    ],
  },
  {
    id: "rs603",
    professionId: "p11",
    gradeLevelId: "g5",
    gradeName: "3rd Grade",
    gradeShortCode: "3",
    description: "Math skills expand to multiplication, division, and fractions — all essential for data work. Conduct your first real data project: survey your class about a topic, organize the results, and present your findings. Learn to spot patterns and outliers. Data science is the art of finding stories in numbers.",
    subjects: ["Math (Multiplication & Division)", "Science (Experiments & Data)", "Reading (Nonfiction)", "Computer Literacy"],
    extracurriculars: [
      { name: "Scratch (MIT)", url: "https://scratch.mit.edu/", description: "Build interactive data visualizations and games — programming meets data storytelling." },
      { name: "Science Fair — Data Analysis Project", url: "", description: "Enter a science fair with a project focused on collecting and analyzing data — survey, measure, graph, conclude." },
    ],
    supplemental: [
      { name: "DK Workbooks: Math (3rd Grade)", url: "", type: "book" },
      { name: "Mystery Science: Data & Patterns", url: "https://mysteryscience.com/", type: "course" },
    ],
  },
  {
    id: "rs604",
    professionId: "p11",
    gradeLevelId: "g6",
    gradeName: "4th Grade",
    gradeShortCode: "4",
    description: "Develop research and data analysis skills. Learn to create and interpret different chart types: line graphs, pie charts, and scatter plots. Start using spreadsheets to organize data. Study statistics in sports — batting averages, shooting percentages, or race times. Data is everywhere once you start looking.",
    subjects: ["Math (Fractions & Decimals)", "Science (Scientific Method)", "English (Research Writing)", "Technology (Spreadsheets)"],
    extracurriculars: [
      { name: "Google Sheets (Family Account)", url: "https://www.google.com/sheets/about/", description: "Learn to enter data, create formulas, and build charts — real tools data scientists use every day." },
      { name: "Math Olympiad", url: "https://www.moems.org/", description: "Challenging math problems that develop the logical and analytical thinking data scientists rely on." },
    ],
    supplemental: [
      { name: "The Manga Guide to Statistics", url: "", type: "book" },
      { name: "Khan Academy: Data and Statistics", url: "https://www.khanacademy.org/math/statistics-probability", type: "course" },
    ],
  },
  {
    id: "rs605",
    professionId: "p11",
    gradeLevelId: "g8",
    gradeName: "6th Grade",
    gradeShortCode: "6",
    description: "Take pre-algebra and any computer classes seriously. Data science lives at the intersection of math and computing. Learn to use spreadsheets for real analysis — formulas, sorting, filtering, and pivot tables. Start thinking about probability: what are the odds? Data scientists use probability to make predictions.",
    subjects: ["Pre-Algebra", "Earth & Data Science", "Computer Skills (Excel/Sheets)", "English (Data Communication)"],
    extracurriculars: [
      { name: "Code.org — CS Discoveries", url: "https://code.org/student/middle-school", description: "Free middle school computer science curriculum introducing data and society, programming, and problem solving." },
      { name: "Science Olympiad — Data Science / Statistics", url: "https://www.soinc.org/", description: "Competitive events building skills in analysis, graphing, and interpreting scientific data." },
    ],
    supplemental: [
      { name: "How to Lie with Statistics — Darrell Huff", url: "", type: "book" },
      { name: "Crash Course: Statistics", url: "https://www.youtube.com/playlist?list=PL8dPuuaLjXtNM_Y-bUAhblSAdWRnmBUcr", type: "video" },
    ],
  },
  {
    id: "rs606",
    professionId: "p11",
    gradeLevelId: "g9",
    gradeName: "7th Grade",
    gradeShortCode: "7",
    description: "Take algebra and science seriously. Start learning Python — it's the most popular language for data science. Explore datasets you care about: sports, music, video games. Track your own data — screen time, exercise, sleep — and look for correlations. Data scientists find meaning in the patterns of everyday life.",
    subjects: ["Algebra I", "Life Science", "Computer Science (Python Intro)", "English (Data Storytelling)"],
    extracurriculars: [
      { name: "DataCamp — Introduction to Python (Free)", url: "https://www.datacamp.com/courses/intro-to-python-for-data-science", description: "Free interactive Python course focused on data science — no installation required." },
      { name: "Kaggle — Titanic: Machine Learning from Disaster", url: "https://www.kaggle.com/c/titanic", description: "The classic beginner data science competition — predict who survived the Titanic using real passenger data." },
    ],
    supplemental: [
      { name: "Python for Kids by Jason R. Briggs", url: "", type: "book" },
      { name: "Khan Academy: Probability & Statistics", url: "https://www.khanacademy.org/math/statistics-probability", type: "course" },
    ],
  },
  {
    id: "rs607",
    professionId: "p11",
    gradeLevelId: "g10",
    gradeName: "8th Grade",
    gradeShortCode: "8",
    description: "Take algebra/geometry and any computer science electives. Deepen Python skills — learn pandas for data manipulation. Explore real-world datasets: census data, climate data, or sports analytics. Build a project: scrape a website, clean the data, analyze it, and create visualizations. This is what data scientists actually do.",
    subjects: ["Algebra I / Geometry", "Physical Science", "Computer Programming (Python)", "Statistics (Intro)", "English (Technical Writing)"],
    extracurriculars: [
      { name: "freeCodeCamp — Data Analysis with Python", url: "https://www.freecodecamp.org/learn/data-analysis-with-python/", description: "Free certification course covering NumPy, pandas, matplotlib, and data cleaning." },
      { name: "Google Science Fair / Data Project", url: "https://www.googlesciencefair.com/", description: "Submit a project using data analysis to answer a scientific question — compete globally." },
    ],
    supplemental: [
      { name: "Naked Statistics — Charles Wheelan", url: "", type: "book" },
      { name: "Jupyter Notebooks (Try online)", url: "https://jupyter.org/try", type: "program" },
    ],
  },
  {
    id: "rs608",
    professionId: "p11",
    gradeLevelId: "g12",
    gradeName: "10th Grade",
    gradeShortCode: "10",
    description: "Take AP Statistics — this is the single most important course for aspiring data scientists. Take AP Computer Science A or Principles. Master Python data libraries: pandas, matplotlib, seaborn. Build a portfolio project on GitHub analyzing a dataset you're passionate about. Apply to summer data science programs.",
    subjects: ["AP Statistics", "AP Computer Science A / Principles", "Pre-Calculus", "English (Research Communication)", "Data Science Elective"],
    extracurriculars: [
      { name: "Data Science for Social Good (High School)", url: "https://www.datascienceforsocialgood.org/", description: "Apply data science to community problems with mentorship from professional data scientists." },
      { name: "NCWIT Aspirations in Computing", url: "https://www.aspirations.org/", description: "National recognition for students in computing — includes data science and AI categories." },
    ],
    supplemental: [
      { name: "Python for Data Analysis — Wes McKinney", url: "", type: "book" },
      { name: "Coursera: Data Science Math Skills (Duke)", url: "https://www.coursera.org/learn/datasciencemathskills", type: "course" },
    ],
  },
  {
    id: "rs609",
    professionId: "p11",
    gradeLevelId: "g13",
    gradeName: "11th Grade",
    gradeShortCode: "11",
    description: "Take AP Calculus and AP Statistics (if both available). Deepen machine learning knowledge — learn scikit-learn and build your first ML model. Research data science programs at top universities. Pursue a data-focused summer internship or research opportunity. Publish your analysis projects on GitHub with clear documentation.",
    subjects: ["AP Calculus AB", "AP Statistics", "AP Computer Science A", "Machine Learning (Self-Study)", "English (Data Journalism)"],
    extracurriculars: [
      { name: "Summer Data Science Programs (University-Based)", url: "https://www.amstat.org/", description: "Apply to university summer data science programs — many offer scholarships for underrepresented students." },
      { name: "Kaggle Competitions (Intermediate)", url: "https://www.kaggle.com/competitions", description: "Compete in real data science challenges with datasets from companies and researchers worldwide." },
    ],
    supplemental: [
      { name: "Introduction to Statistical Learning (Free PDF)", url: "https://www.statlearning.com/", type: "book" },
      { name: "Andrew Ng — Machine Learning (Coursera)", url: "https://www.coursera.org/learn/machine-learning", type: "course" },
    ],
  },
  {
    id: "rs610",
    professionId: "p11",
    gradeLevelId: "g16",
    gradeName: "Graduate",
    gradeShortCode: "grad",
    description: "Pursue an M.S. in Data Science, Statistics, Machine Learning, or Computer Science with an AI/ML focus. Specialize in a domain: healthcare analytics, financial modeling, NLP, computer vision, or causal inference. Complete a capstone project with real-world impact. Top tech companies aggressively recruit data science graduate students for roles paying $150K+.",
    subjects: ["Advanced Machine Learning", "Deep Learning", "Big Data Systems", "Bayesian Statistics", "Capstone / Thesis"],
    extracurriculars: [
      { name: "Google AI Residency", url: "https://research.google/careers/ai-residency/", description: "One-year research training program for aspiring ML researchers from diverse backgrounds." },
      { name: "Data Science Conferences (NeurIPS, KDD, ICML)", url: "https://neurips.cc/", description: "Attend and present at top-tier data science and machine learning conferences." },
    ],
    supplemental: [
      { name: "Deep Learning — Goodfellow, Bengio & Courville", url: "https://www.deeplearningbook.org/", type: "book" },
      { name: "Papers with Code", url: "https://paperswithcode.com/", type: "article" },
    ],
  },
  {
    id: "rs611",
    professionId: "p11",
    gradeLevelId: "g17",
    gradeName: "PhD / Doctoral",
    gradeShortCode: "phd",
    description: "A Ph.D. in Statistics, Machine Learning, Computer Science (AI track), or a quantitative field positions you for research scientist roles at top tech companies, national labs, or academia. Focus on cutting-edge areas: reinforcement learning, causal inference, AI safety, or computational statistics. Publish at top conferences and journals.",
    subjects: ["Advanced Statistical Theory", "Machine Learning Research", "Dissertation", "Teaching / Mentoring", "Grant Writing"],
    extracurriculars: [
      { name: "NSF Graduate Research Fellowship", url: "https://www.nsfgrfp.org/", description: "Prestigious fellowship funding graduate research in STEM — data science and AI are priority areas." },
      { name: "Research Internships (Google Research, Meta AI, Microsoft Research)", url: "https://research.google/careers/", description: "Paid Ph.D. internships at industry research labs — often lead to full-time research positions." },
    ],
    supplemental: [
      { name: "Journal of Machine Learning Research (JMLR)", url: "https://www.jmlr.org/", type: "article" },
      { name: "arXiv — Statistics & Machine Learning", url: "https://arxiv.org/list/stat.ML/recent", type: "article" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // p14 — Civil Engineer (all 17 grades)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "rs612",
    professionId: "p14",
    gradeLevelId: "g1",
    gradeName: "Pre-K",
    gradeShortCode: "prek",
    description: "Civil engineering begins with building and creating! At this age, children explore structures through block play, sandboxes, and construction toys. Encourage building bridges with blocks, digging canals in the sand, and asking: 'How can we make this taller? Stronger?' The impulse to build and improve the world around us starts here.",
    subjects: ["Building & Construction Play", "Shapes & Spatial Awareness", "Curiosity About Structures", "Fine Motor Skills"],
    extracurriculars: [
      { name: "LEGO DUPLO Construction Sets", url: "https://www.lego.com/en-us/themes/duplo", description: "Large building blocks that develop spatial reasoning and understanding of structure and balance." },
      { name: "Children's Museums — Construction Zones", url: "https://www.childrensmuseums.org/", description: "Hands-on building exhibits with bridges, tunnels, and water play that teach basic engineering concepts." },
    ],
    supplemental: [
      { name: "Goodnight, Goodnight, Construction Site by Sherri Duskey Rinker", url: "", type: "book" },
      { name: "Iggy Peck, Architect by Andrea Beaty", url: "", type: "book" },
    ],
  },
  {
    id: "rs613",
    professionId: "p14",
    gradeLevelId: "g2",
    gradeName: "Kindergarten",
    gradeShortCode: "k",
    description: "Build spatial reasoning and creative problem-solving through construction play. Draw bridges, roads, and buildings. Notice the infrastructure in your community — the roads you travel on, the bridges you cross, the pipes that bring water to your home. Civil engineers design the invisible systems that make modern life possible.",
    subjects: ["Drawing & Design", "Counting & Measuring", "Early Science (Water & Materials)", "Community Awareness"],
    extracurriculars: [
      { name: "PBS Kids — Design Squad", url: "https://pbskids.org/designsquad/", description: "Engineering challenges for young children — build bridges, towers, and structures from everyday materials." },
      { name: "Local Bridge & Building Walks", url: "", description: "Walk around your neighborhood and identify different types of bridges, buildings, and infrastructure." },
    ],
    supplemental: [
      { name: "Dreaming Up: A Celebration of Building by Christy Hale", url: "", type: "book" },
      { name: "How a House Is Built by Gail Gibbons", url: "", type: "book" },
    ],
  },
  {
    id: "rs614",
    professionId: "p14",
    gradeLevelId: "g3",
    gradeName: "1st Grade",
    gradeShortCode: "1",
    description: "Strengthen math and reading — civil engineers use math for measurements and calculations, and reading for codes and plans. Learn about different materials: wood, concrete, steel, and why engineers choose different materials for different projects. Build a model bridge from popsicle sticks and test how much weight it can hold.",
    subjects: ["Reading & Writing", "Math (Addition & Measurement)", "Science (Materials)", "Art (Building Models)"],
    extracurriculars: [
      { name: "Science Buddies — Bridge Building", url: "https://www.sciencebuddies.org/", description: "Free engineering projects teaching structural principles through hands-on bridge and tower building." },
      { name: "LEGO Bridge Challenge", url: "", description: "Build bridges with LEGOs spanning a gap and test their strength — a perfect introduction to structural engineering." },
    ],
    supplemental: [
      { name: "Bridges Are to Cross by Philemon Sturges", url: "", type: "book" },
      { name: "National Geographic Kids: Engineering", url: "https://kids.nationalgeographic.com/science/article/engineering", type: "article" },
    ],
  },
  {
    id: "rs615",
    professionId: "p14",
    gradeLevelId: "g4",
    gradeName: "2nd Grade",
    gradeShortCode: "2",
    description: "Deepen understanding of how structures work. Learn about forces: pushing, pulling, bending, and breaking. Civil engineers must ensure bridges don't collapse and buildings withstand wind and earthquakes. Build models of different bridge types: beam, arch, and suspension. Test materials to see which is strongest.",
    subjects: ["Reading Comprehension", "Math (Measurement & Geometry)", "Science (Forces & Materials)", "Art (Structural Drawing)"],
    extracurriculars: [
      { name: "PBS Kids — Fetch! with Ruff Ruffman", url: "https://pbskids.org/fetch/", description: "Engineering challenges including bridge building, tower construction, and structural testing." },
      { name: "Minecraft — Engineering Mode", url: "https://www.minecraft.net/", description: "Design and build bridges, dams, and cities in a virtual environment that teaches structural thinking." },
    ],
    supplemental: [
      { name: "Building Big by David Macaulay", url: "", type: "book" },
      { name: "BrainPOP: Bridges", url: "https://www.brainpop.com/technology/scienceandindustry/bridges/", type: "video" },
    ],
  },
  {
    id: "rs616",
    professionId: "p14",
    gradeLevelId: "g5",
    gradeName: "3rd Grade",
    gradeShortCode: "3",
    description: "Expand math to include multiplication, division, and fractions — essential for scaling designs. Learn about the world's greatest civil engineering projects: the Golden Gate Bridge, Panama Canal, Hoover Dam, and Burj Khalifa. Study how water systems work: where does your drinking water come from and where does it go?",
    subjects: ["Math (Fractions & Decimals)", "Science (Earth & Water Systems)", "Social Studies (World Infrastructure)", "Art (Design Drawing)"],
    extracurriculars: [
      { name: "Engineering for Kids — After School", url: "https://engineeringforkids.com/", description: "Hands-on programs exploring civil, structural, and environmental engineering for elementary students." },
      { name: "Future City Competition (Junior)", url: "https://futurecity.org/", description: "Design a city of the future — combines urban planning, infrastructure, and civil engineering for grades 6-8." },
    ],
    supplemental: [
      { name: "DK Findout! Engineering", url: "https://www.dkfindout.com/us/science/engineering/", type: "article" },
      { name: "Crash Course Kids: Engineering", url: "https://www.youtube.com/playlist?list=PLhz12vamHOnZ4ZDC0dS6C9HRN5Qrm0jHO", type: "video" },
    ],
  },
  {
    id: "rs617",
    professionId: "p14",
    gradeLevelId: "g6",
    gradeName: "4th Grade",
    gradeShortCode: "4",
    description: "Develop research and analytical skills — civil engineers research site conditions, environmental impact, and building codes. Study famous engineering failures and what we learned: the Tacoma Narrows Bridge collapse, the Hyatt Regency walkway. Good engineers learn from mistakes. Math now includes more geometry and proportions.",
    subjects: ["English (Research Writing)", "Math (Geometry & Proportions)", "Science (Earth Science)", "Social Studies (Engineering History)"],
    extracurriculars: [
      { name: "Science Olympiad — Bridge / Tower Events", url: "https://www.soinc.org/", description: "Build and test balsa wood structures — apply civil engineering principles in competition." },
      { name: "4-H Engineering & Technology", url: "https://4-h.org/programs/stem/", description: "Youth engineering projects including bridge design, water systems, and construction technology." },
    ],
    supplemental: [
      { name: "Why Buildings Fall Down — Matthys Levy & Mario Salvadori", url: "", type: "book" },
      { name: "Mystery Science: Invisible Forces", url: "https://mysteryscience.com/", type: "course" },
    ],
  },
  {
    id: "rs618",
    professionId: "p14",
    gradeLevelId: "g7",
    gradeName: "5th Grade",
    gradeShortCode: "5",
    description: "Civil engineering requires strong math and science foundations. Focus on geometry, measurement, and earth science. Learn about structural loads: dead load (weight of the structure), live load (people/furniture), and environmental load (wind, snow, earthquakes). Build a spaghetti bridge and test it to destruction — the best way to learn!",
    subjects: ["Math (Pre-Algebra & Geometry)", "Earth Science", "General Science (Physics of Structures)", "Art (Technical Drawing)"],
    extracurriculars: [
      { name: "FIRST LEGO League", url: "https://www.firstlegoleague.org/", description: "Design and build LEGO robots to solve challenges — structural thinking and teamwork." },
      { name: "ACE Mentor Program (Prep)", url: "https://www.acementor.org/", description: "After-school program connecting students with architecture, construction, and engineering professionals (starts middle school)." },
    ],
    supplemental: [
      { name: "The Art of Construction — Mario Salvadori", url: "", type: "book" },
      { name: "Khan Academy: Geometry", url: "https://www.khanacademy.org/math/geometry", type: "course" },
    ],
  },
  {
    id: "rs619",
    professionId: "p14",
    gradeLevelId: "g8",
    gradeName: "6th Grade",
    gradeShortCode: "6",
    description: "Take pre-algebra and earth science seriously — they're the gateway to civil engineering. Learn about soil mechanics: why some soils can support skyscrapers and others can't. Study water resources: dams, levees, and flood control. Join a STEM club or start one. Civil engineers solve community-scale problems.",
    subjects: ["Pre-Algebra", "Earth Science (Geology & Water)", "Physical Science", "English (Technical Reading)"],
    extracurriculars: [
      { name: "Future City Competition", url: "https://futurecity.org/", description: "Design a city 100 years in the future — address infrastructure, sustainability, and urban planning challenges." },
      { name: "SeaPerch Underwater Robotics", url: "https://seaperch.org/", description: "Build an underwater ROV — combines civil, mechanical, and electrical engineering with water systems thinking." },
    ],
    supplemental: [
      { name: "Structures: Or Why Things Don't Fall Down — J.E. Gordon", url: "", type: "book" },
      { name: "Tinkercad — 3D Design (Free)", url: "https://www.tinkercad.com/", type: "program" },
    ],
  },
  {
    id: "rs620",
    professionId: "p14",
    gradeLevelId: "g9",
    gradeName: "7th Grade",
    gradeShortCode: "7",
    description: "Take algebra and earth science seriously. Learn about the different civil engineering disciplines: structural, geotechnical, transportation, environmental, and water resources. Start learning CAD software. Visit a construction site or civil engineering firm. Civil engineers shape the physical world — roads, bridges, buildings, and water systems.",
    subjects: ["Algebra I", "Earth Science / Geology", "Computer-Aided Design (CAD)", "English (Technical Writing)"],
    extracurriculars: [
      { name: "ACE Mentor Program", url: "https://www.acementor.org/", description: "Free after-school program connecting students with civil, structural, and construction engineering professionals." },
      { name: "MESA (Mathematics, Engineering, Science Achievement)", url: "https://mesa.ucop.edu/", description: "Engineering design competitions including structural and environmental challenges." },
    ],
    supplemental: [
      { name: "Fusion 360 (Free for Students)", url: "https://www.autodesk.com/education/edu-software/fusion", type: "program" },
      { name: "How It's Made (YouTube)", url: "https://www.youtube.com/show/howitsmade", type: "video" },
    ],
  },
  {
    id: "rs621",
    professionId: "p14",
    gradeLevelId: "g10",
    gradeName: "8th Grade",
    gradeShortCode: "8",
    description: "Take geometry and physical science. Design a model bridge in CAD and 3D print it. Research civil engineering programs — civil is one of the oldest and broadest engineering disciplines. Learn about sustainability and green building: how can we design infrastructure that works with nature instead of against it?",
    subjects: ["Geometry", "Physical Science", "Environmental Science", "Computer Programming (Python intro)", "English (Technical Communication)"],
    extracurriculars: [
      { name: "NASA HUNCH Program", url: "https://www.nasahunch.com/", description: "Design and build real hardware — includes structural and systems engineering challenges for NASA." },
      { name: "Civil Engineering Summer Camps (University-Based)", url: "https://www.asce.org/", description: "Many universities offer summer engineering camps — explore structural, environmental, and geotechnical engineering." },
    ],
    supplemental: [
      { name: "The Works: Anatomy of a City — Kate Ascher", url: "", type: "book" },
      { name: "MIT OpenCourseWare: Introduction to Civil Engineering", url: "https://ocw.mit.edu/courses/1-012-introduction-to-civil-engineering-design-spring-2002/", type: "course" },
    ],
  },
  {
    id: "rs622",
    professionId: "p14",
    gradeLevelId: "g11",
    gradeName: "9th Grade",
    gradeShortCode: "9",
    description: "Take Honors Physics and advanced math. Physics is the foundation of structural engineering — understanding forces, moments, and material behavior. Join a robotics or engineering club. Civil engineers need strong analytical skills and creativity. Research ABET-accredited civil engineering programs and their focus areas.",
    subjects: ["Honors Physics", "Algebra II", "Chemistry", "Engineering Design Elective", "English (Research Writing)"],
    extracurriculars: [
      { name: "FIRST Robotics Competition (FRC)", url: "https://www.firstinspires.org/robotics/frc", description: "Build competition robots — develops structural design, mechanical systems, and teamwork skills." },
      { name: "American Society of Civil Engineers (ASCE) — Student Resources", url: "https://www.asce.org/", description: "Explore civil engineering career paths, scholarships, and student competitions." },
    ],
    supplemental: [
      { name: "Khan Academy: Physics", url: "https://www.khanacademy.org/science/physics", type: "course" },
      { name: "Bridges: The Spans of North America — David Plowden", url: "", type: "book" },
    ],
  },
  {
    id: "rs623",
    professionId: "p14",
    gradeLevelId: "g12",
    gradeName: "10th Grade",
    gradeShortCode: "10",
    description: "Take AP Physics 1 and Pre-Calculus — these are prerequisites for civil engineering programs. Learn about surveying and site analysis. Participate in infrastructure-related projects: measure traffic flow, test water quality, or map your neighborhood. Civil engineers improve the communities they live in.",
    subjects: ["AP Physics 1", "Pre-Calculus", "AP Environmental Science", "Engineering Design / CAD", "English (Technical Reports)"],
    extracurriculars: [
      { name: "ACE Mentor Program — Advanced Projects", url: "https://www.acementor.org/", description: "Work on real civil engineering design projects with professional mentors — build your portfolio." },
      { name: "Environmental Science Club / Water Testing", url: "", description: "Test local water quality, study watershed management, and propose infrastructure improvements." },
    ],
    supplemental: [
      { name: "Civil Engineering Body of Knowledge (ASCE)", url: "https://www.asce.org/", type: "article" },
      { name: "Coursera: Sustainable Urban Development (TU Delft)", url: "https://www.coursera.org/learn/sustainable-urban-development", type: "course" },
    ],
  },
  {
    id: "rs624",
    professionId: "p14",
    gradeLevelId: "g13",
    gradeName: "11th Grade",
    gradeShortCode: "11",
    description: "Take AP Physics C (calculus-based) and AP Calculus AB — these are direct college equivalents. Civil engineering is math-intensive. Research specific civil engineering programs: structural, transportation, geotechnical, environmental, or construction management. Visit university engineering departments. Apply for engineering summer programs.",
    subjects: ["AP Physics C: Mechanics", "AP Calculus AB", "AP Chemistry", "Computer Science (Matlab/Python)", "English (College Essays)"],
    extracurriculars: [
      { name: "ASCE Civil Engineering Competition (High School)", url: "https://www.asce.org/", description: "Some ASCE chapters host high school competitions — bridge building, concrete canoe, and sustainable design." },
      { name: "Engineering Internship / Job Shadow", url: "", description: "Contact local civil engineering firms about summer internships or job shadowing opportunities." },
    ],
    supplemental: [
      { name: "FE Exam — Preview Materials (NCEES)", url: "https://ncees.org/engineering/fe/", type: "program" },
      { name: "To Engineer Is Human — Henry Petroski", url: "", type: "book" },
    ],
  },
  {
    id: "rs625",
    professionId: "p14",
    gradeLevelId: "g14",
    gradeName: "12th Grade",
    gradeShortCode: "12",
    description: "Apply to ABET-accredited civil engineering programs. Take AP Calculus BC and AP Physics C exams for college credit. Research schools with strong co-op programs — civil engineering students benefit enormously from paid work experience. Write application essays about infrastructure projects that inspire you and problems you want to solve.",
    subjects: ["AP Calculus BC", "AP Physics C (E&M)", "AP Environmental Science", "Engineering Capstone", "AP English Literature"],
    extracurriculars: [
      { name: "ASCE Scholarship Applications", url: "https://www.asce.org/", description: "ASCE awards hundreds of thousands in scholarships annually to civil engineering students." },
      { name: "Senior Engineering Project", url: "", description: "Design and build a civil engineering project — a footbridge, rainwater collection system, or erosion control structure." },
    ],
    supplemental: [
      { name: "ABET — Find Accredited Programs", url: "https://www.abet.org/", type: "article" },
      { name: "Engineer Your Future (ASCE Career Guide)", url: "https://www.asce.org/", type: "article" },
    ],
  },
  {
    id: "rs626",
    professionId: "p14",
    gradeLevelId: "g15",
    gradeName: "Undergraduate",
    gradeShortCode: "ugrad",
    description: "Pursue a B.S. in Civil Engineering from an ABET-accredited program. Core coursework: statics, dynamics, mechanics of materials, structural analysis, fluid mechanics, geotechnical engineering, transportation, and environmental engineering. Take the FE (Fundamentals of Engineering) exam before graduation. Pursue internships every summer.",
    subjects: ["Structural Analysis", "Fluid Mechanics & Hydraulics", "Geotechnical Engineering", "Transportation Engineering", "Environmental Engineering"],
    extracurriculars: [
      { name: "ASCE Student Chapter", url: "https://www.asce.org/", description: "Join your university's ASCE chapter — concrete canoe, steel bridge, and sustainable design competitions." },
      { name: "Engineers Without Borders", url: "https://www.ewb-usa.org/", description: "Design and build infrastructure projects for communities in need — real-world civil engineering experience." },
    ],
    supplemental: [
      { name: "FE Civil Exam Prep (NCEES)", url: "https://ncees.org/engineering/fe/", type: "program" },
      { name: "AutoCAD Civil 3D (Student License)", url: "https://www.autodesk.com/education/edu-software/", type: "program" },
    ],
  },
  {
    id: "rs627",
    professionId: "p14",
    gradeLevelId: "g16",
    gradeName: "Graduate",
    gradeShortCode: "grad",
    description: "Pursue an M.S. in Civil Engineering to specialize in structural, geotechnical, transportation, environmental, or construction management. A master's is increasingly expected for leadership roles. Complete the PE (Professional Engineer) license process: EIT certification → 4 years of experience → PE exam. PEs can sign and seal engineering plans.",
    subjects: ["Advanced Structural Design", "Finite Element Analysis", "Foundation Engineering", "Construction Management", "Thesis / Capstone"],
    extracurriculars: [
      { name: "ASCE Graduate Student Leadership", url: "https://www.asce.org/", description: "Graduate-level ASCE involvement — technical committees, conference presentations, and professional networking." },
      { name: "Structural Engineers Association (SEA) — Student Programs", url: "https://www.seaint.org/", description: "Professional organization for structural engineers — mentorship, technical seminars, and job connections." },
    ],
    supplemental: [
      { name: "PE Civil Exam Prep (NCEES)", url: "https://ncees.org/engineering/pe/civil/", type: "program" },
      { name: "ASCE 7: Minimum Design Loads for Buildings", url: "", type: "book" },
    ],
  },
  {
    id: "rs628",
    professionId: "p14",
    gradeLevelId: "g17",
    gradeName: "PhD / Doctoral",
    gradeShortCode: "phd",
    description: "A Ph.D. in Civil Engineering is for those pursuing academic careers, advanced research at national labs, or specialized consulting. Research areas: earthquake engineering, sustainable materials, smart infrastructure, or climate-resilient design. Civil engineering Ph.D.s lead the research that makes our infrastructure safer, greener, and smarter.",
    subjects: ["Advanced Research Methods", "Specialized Dissertation Research", "Structural Dynamics / Geotechnical Modeling", "Teaching Practicum", "Grant Writing & Publishing"],
    extracurriculars: [
      { name: "NSF Graduate Research Fellowship (GRFP)", url: "https://www.nsfgrfp.org/", description: "Prestigious fellowship funding Ph.D. research in engineering — civil engineering is a priority area." },
      { name: "National Labs Research (NIST, USACE, FHWA)", url: "https://orise.orau.gov/internships-fellowships/", description: "Paid research opportunities at federal labs working on national infrastructure challenges." },
    ],
    supplemental: [
      { name: "Journal of Structural Engineering (ASCE)", url: "https://ascelibrary.org/journal/jsendh", type: "article" },
      { name: "The Civil Engineering Handbook", url: "", type: "book" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // p15 — Psychologist (all 17 grades)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "rs629",
    professionId: "p15",
    gradeLevelId: "g1",
    gradeName: "Pre-K",
    gradeShortCode: "prek",
    description: "Psychology begins with understanding feelings — our own and others'. At this age, children learn to name emotions, practice empathy, and notice how people are similar and different. Encourage talking about feelings, reading books with emotional themes, and playing cooperatively. The seeds of psychological insight are planted in early emotional learning.",
    subjects: ["Social-Emotional Learning", "Language (Feelings Words)", "Cooperation & Sharing", "Observing Others"],
    extracurriculars: [
      { name: "Sesame Street — Emotional Wellbeing", url: "https://sesamestreet.org/", description: "Videos and activities about feelings, empathy, and getting along with others — foundational emotional intelligence." },
      { name: "Daniel Tiger's Neighborhood (PBS Kids)", url: "https://pbskids.org/daniel/", description: "Episodes focused on emotions, social skills, and understanding how others feel." },
    ],
    supplemental: [
      { name: "The Color Monster by Anna Llenas", url: "", type: "book" },
      { name: "In My Heart: A Book of Feelings by Jo Witek", url: "", type: "book" },
    ],
  },
  {
    id: "rs630",
    professionId: "p15",
    gradeLevelId: "g2",
    gradeName: "Kindergarten",
    gradeShortCode: "k",
    description: "Build emotional vocabulary and social awareness. Learn to identify emotions in yourself and others — happy, sad, angry, scared, surprised. Practice calming strategies when upset. Notice how people's faces and bodies show what they're feeling. Psychologists spend their careers understanding the mind — and it starts with understanding our own feelings.",
    subjects: ["Reading (Emotion-Themed Books)", "Social Skills", "Early Science (The Brain & Body)", "Art (Drawing Feelings)"],
    extracurriculars: [
      { name: "Mind Yeti — Mindfulness for Kids", url: "https://www.mindyeti.com/", description: "Free mindfulness audio sessions for young children — learn to notice thoughts and feelings." },
      { name: "Local Library Social-Emotional Storytime", url: "https://www.ala.org/", description: "Many libraries host storytimes focused on feelings, friendship, and understanding others." },
    ],
    supplemental: [
      { name: "The Rabbit Listened by Cori Doerrfeld", url: "", type: "book" },
      { name: "Listening to My Body by Gabi Garcia", url: "", type: "book" },
    ],
  },
  {
    id: "rs631",
    professionId: "p15",
    gradeLevelId: "g3",
    gradeName: "1st Grade",
    gradeShortCode: "1",
    description: "Build reading and communication skills — psychologists read constantly (research, case studies, assessments) and communicate with patients, families, and colleagues. Practice being a good listener. Notice how different people react to the same situation. Start a 'feelings journal' where you draw or write about emotions each day.",
    subjects: ["Reading & Writing", "Math (Patterns & Data)", "Science (How Our Brains Work)", "Social Studies (Families & Communities)"],
    extracurriculars: [
      { name: "KidsHealth.org — Your Mind", url: "https://kidshealth.org/en/kids/", description: "Free articles and videos about feelings, brain science, and mental health written for children." },
      { name: "Peaceful Kids / Mindfulness Programs", url: "", description: "School or community programs teaching mindfulness, emotional regulation, and empathy." },
    ],
    supplemental: [
      { name: "A Little Spot of Emotion Box Set by Diane Alber", url: "", type: "book" },
      { name: "BrainPOP Jr.: Emotions", url: "https://jr.brainpop.com/health/emotions/", type: "video" },
    ],
  },
  {
    id: "rs632",
    professionId: "p15",
    gradeLevelId: "g4",
    gradeName: "2nd Grade",
    gradeShortCode: "2",
    description: "Deepen understanding of how people think and feel. Learn about the brain — the organ behind all thoughts, feelings, and behaviors. Practice observing social dynamics: how do groups work? Why do people act differently alone versus with friends? Read biographies of famous psychologists and what they discovered about human nature.",
    subjects: ["Reading Comprehension", "Writing (Journal Prompts)", "Science (Brain & Nervous System)", "Social Studies (Human Behavior)"],
    extracurriculars: [
      { name: "National Geographic Kids: Your Amazing Brain", url: "https://kids.nationalgeographic.com/science/article/your-amazing-brain", description: "Interactive article exploring how the brain works — memory, emotions, and learning." },
      { name: "Girls on the Run / Social-Emotional Programs", url: "https://www.girlsontherun.org/", description: "Program combining physical activity with lessons on emotions, relationships, and self-confidence." },
    ],
    supplemental: [
      { name: "Your Fantastic Elastic Brain by JoAnn Deak", url: "", type: "book" },
      { name: "DK Findout! Human Body — Brain Section", url: "https://www.dkfindout.com/us/science/human-body/brain/", type: "article" },
    ],
  },
  {
    id: "rs633",
    professionId: "p15",
    gradeLevelId: "g5",
    gradeName: "3rd Grade",
    gradeShortCode: "3",
    description: "Learn about psychology's big questions: Why do we dream? How do memories work? What makes people happy? Start conducting simple 'experiments' — observe how people behave in different situations and write down what you notice. Math skills (multiplication, division, fractions) are essential for analyzing data in psychological research.",
    subjects: ["Math (Fractions & Data)", "Science (Human Biology)", "Reading (Nonfiction Psychology Books)", "Writing (Research Notes)"],
    extracurriculars: [
      { name: "Science Fair — Psychology Project", url: "", description: "Design a psychology experiment for the school science fair — test memory, perception, or social behavior." },
      { name: "Chess Club / Strategy Games", url: "", description: "Strategy games develop understanding of decision-making, planning, and how people think under pressure." },
    ],
    supplemental: [
      { name: "Psychology for Kids: The Science of the Mind by Jonni Kincher", url: "", type: "book" },
      { name: "National Geographic Kids Brain Games", url: "https://kids.nationalgeographic.com/games/", type: "program" },
    ],
  },
  {
    id: "rs634",
    professionId: "p15",
    gradeLevelId: "g6",
    gradeName: "4th Grade",
    gradeShortCode: "4",
    description: "Develop research and observation skills — psychologists are scientists who study the mind. Learn about famous psychology experiments: Pavlov's dogs, the Stanford marshmallow test, and Milgram's obedience study. Understand that psychology uses the scientific method just like biology or chemistry. People are fascinating subjects to study!",
    subjects: ["English (Research & Analysis)", "Math (Statistics Intro)", "Science (Scientific Method in Social Science)", "Social Studies (Culture & Behavior)"],
    extracurriculars: [
      { name: "Science Olympiad — Experimental Design", url: "https://www.soinc.org/", description: "Competitive event teaching experimental design, data collection, and analysis — core psychology research skills." },
      { name: "Odyssey of the Mind", url: "https://www.odysseyofthemind.com/", description: "Creative problem-solving competition that develops teamwork, perspective-taking, and creative thinking." },
    ],
    supplemental: [
      { name: "The Kid's Guide to Exploring the Mind (APA)", url: "https://www.apa.org/", type: "article" },
      { name: "Mystery Science: Social & Emotional Learning", url: "https://mysteryscience.com/", type: "course" },
    ],
  },
  {
    id: "rs635",
    professionId: "p15",
    gradeLevelId: "g7",
    gradeName: "5th Grade",
    gradeShortCode: "5",
    description: "Build strong reading, writing, and math skills — psychology is a reading-and-writing-intensive science. Learn about the different branches of psychology: clinical, developmental, social, cognitive, neuroscience, and more. Start a 'human behavior journal' where you record interesting observations about how people think and act.",
    subjects: ["English Language Arts", "Math (Pre-Algebra & Data)", "Life Science (Brain & Body)", "Social Studies (Why People Behave as They Do)"],
    extracurriculars: [
      { name: "National History Day — Psychology Topic", url: "https://www.nhd.org/", description: "Research a psychology-related historical topic — the history of mental health treatment or a famous psychologist." },
      { name: "Peer Mediation / Conflict Resolution Programs", url: "", description: "Train as a peer mediator — learn to help others resolve conflicts, practice active listening, and understand perspectives." },
    ],
    supplemental: [
      { name: "The Psychology Book: Big Ideas Simply Explained (DK)", url: "", type: "book" },
      { name: "Crash Course: Psychology", url: "https://www.youtube.com/playlist?list=PL8dPuuaLjXtOPRKzVLY0jJY-uHOH9KVU6", type: "video" },
    ],
  },
  {
    id: "rs636",
    professionId: "p15",
    gradeLevelId: "g8",
    gradeName: "6th Grade",
    gradeShortCode: "6",
    description: "Take science and English seriously. Learn about adolescent brain development — your own brain is undergoing massive changes right now! Study how hormones affect mood and behavior. Read about mental health, resilience, and well-being. Consider volunteering as a peer tutor or mentor — practice understanding and helping others.",
    subjects: ["English (Critical Thinking)", "Pre-Algebra", "Life Science (Brain & Development)", "Health Education"],
    extracurriculars: [
      { name: "National Junior Honor Society — Service Projects", url: "https://www.njhs.us/", description: "Volunteer service projects that develop empathy, leadership, and understanding of community needs." },
      { name: "Youth Mental Health First Aid (Intro Resources)", url: "https://www.mentalhealthfirstaid.org/", description: "Learn about mental health awareness and how to support friends who might be struggling." },
    ],
    supplemental: [
      { name: "The 7 Habits of Highly Effective Teens — Sean Covey", url: "", type: "book" },
      { name: "TED-Ed: The Science of Emotions", url: "https://ed.ted.com/lessons?category=psychology", type: "video" },
    ],
  },
  {
    id: "rs637",
    professionId: "p15",
    gradeLevelId: "g9",
    gradeName: "7th Grade",
    gradeShortCode: "7",
    description: "Take biology and English seriously. Pay special attention to units on the nervous system and brain. Start reading psychology books written for a general audience. Volunteer at a nursing home, mentor younger students, or work with kids — psychologists work with people of all ages and need strong interpersonal skills.",
    subjects: ["Algebra I", "Life Science / Biology", "English (Psychology Reading)", "Foreign Language", "Health / Social Studies"],
    extracurriculars: [
      { name: "Psychology Club (Start One!)", url: "", description: "Start a psychology club at your school — discuss interesting studies, watch TED talks, and explore careers in mental health." },
      { name: "Crisis Text Line — Learn About Mental Health", url: "https://www.crisistextline.org/", description: "Learn about mental health support — when you're older, you can train as a volunteer crisis counselor." },
    ],
    supplemental: [
      { name: "Thinking, Fast and Slow (Adapted summaries for teens)", url: "", type: "book" },
      { name: "Khan Academy: MCAT Psychology & Sociology", url: "https://www.khanacademy.org/test-prep/mcat", type: "course" },
    ],
  },
  {
    id: "rs638",
    professionId: "p15",
    gradeLevelId: "g10",
    gradeName: "8th Grade",
    gradeShortCode: "8",
    description: "Take the most advanced science available. Learn about research methods: how do psychologists design experiments and analyze data? Study different psychological disorders and how they're treated. Consider the career paths: clinical psychologist, school psychologist, research psychologist, industrial-organizational psychologist. All require a doctoral degree.",
    subjects: ["Geometry / Algebra II", "Biology (Advanced)", "English (Research Writing)", "Health / Intro Psychology"],
    extracurriculars: [
      { name: "NAMI — National Alliance on Mental Illness (Youth Programs)", url: "https://www.nami.org/", description: "Learn about mental health advocacy, reduce stigma, and participate in awareness activities." },
      { name: "Active Minds (Middle School)", url: "https://www.activeminds.org/", description: "Student-led mental health awareness and education — change the conversation about mental health at your school." },
    ],
    supplemental: [
      { name: "The Man Who Mistook His Wife for a Hat — Oliver Sacks", url: "", type: "book" },
      { name: "Coursera: Introduction to Psychology (Yale)", url: "https://www.coursera.org/learn/introduction-psychology", type: "course" },
    ],
  },
  {
    id: "rs639",
    professionId: "p15",
    gradeLevelId: "g11",
    gradeName: "9th Grade",
    gradeShortCode: "9",
    description: "Take Honors Biology and any psychology electives. The brain and nervous system are the biological bases of behavior. Study statistics — psychological research depends on statistical analysis. Volunteer in settings where you interact with diverse people: hospitals, schools, shelters, or community centers. Psychology is about understanding the human experience.",
    subjects: ["Honors Biology", "Algebra II", "Psychology Elective (if available)", "Statistics", "English (Scientific Writing)"],
    extracurriculars: [
      { name: "HOSA — Behavioral Health Events", url: "https://hosa.org/", description: "Compete in psychology, mental health, and behavioral science events through HOSA." },
      { name: "Peer Counseling / Mentoring Programs", url: "", description: "Train as a peer counselor — many high schools offer programs where students support each other." },
    ],
    supplemental: [
      { name: "Quiet: The Power of Introverts — Susan Cain (Young Readers)", url: "", type: "book" },
      { name: "APA — Psychology as a Career", url: "https://www.apa.org/education-career/guide/careers", type: "article" },
    ],
  },
  {
    id: "rs640",
    professionId: "p15",
    gradeLevelId: "g12",
    gradeName: "10th Grade",
    gradeShortCode: "10",
    description: "Take AP Psychology — the most direct preparation. Take AP Biology and AP Statistics as well. These three AP courses form the ideal foundation for a psychology major. Research different psychology career paths: clinical, counseling, school, forensic, sports, neuropsychology. Shadow a psychologist if possible.",
    subjects: ["AP Psychology", "AP Biology", "AP Statistics", "English (Research & Analysis)", "Sociology / Anthropology Elective"],
    extracurriculars: [
      { name: "APA TOPSS (Teachers of Psychology in Secondary Schools)", url: "https://www.apa.org/ed/precollege/topss/", description: "High school psychology resources — competitions, lesson plans, and career exploration." },
      { name: "Summer Psychology Programs (University-Based)", url: "https://www.apa.org/", description: "Apply to university summer programs exploring psychology, neuroscience, and mental health careers." },
    ],
    supplemental: [
      { name: "The Happiness Advantage — Shawn Achor", url: "", type: "book" },
      { name: "Crash Course: AP Psychology", url: "https://www.youtube.com/playlist?list=PL8dPuuaLjXtOPRKzVLY0jJY-uHOH9KVU6", type: "video" },
    ],
  },
  {
    id: "rs641",
    professionId: "p15",
    gradeLevelId: "g13",
    gradeName: "11th Grade",
    gradeShortCode: "11",
    description: "Take advanced science and statistics courses. Psychology is a STEM discipline grounded in research methodology. Conduct an independent research project — design a survey, collect data, and analyze results. Research universities with strong psychology and neuroscience programs. Consider the long educational path: 4 years undergrad + 5-7 years Ph.D.",
    subjects: ["AP Biology / AP Chemistry", "AP Statistics", "Pre-Calculus / Calculus", "AP English (Research Writing)", "Psychology Independent Study"],
    extracurriculars: [
      { name: "Research Science Institute (RSI) — Social Science Track", url: "https://www.cee.org/programs/research-science-institute", description: "Highly selective summer research program — conduct original psychology/neuroscience research with university mentors." },
      { name: "Local Crisis Hotline / Helpline Volunteer (Age 16+)", url: "", description: "Some crisis lines train older teens — profound experience in active listening and supporting people in distress." },
    ],
    supplemental: [
      { name: "The Body Keeps the Score — Bessel van der Kolk", url: "", type: "book" },
      { name: "Coursera: Social Psychology (Wesleyan)", url: "https://www.coursera.org/learn/social-psychology", type: "course" },
    ],
  },
  {
    id: "rs642",
    professionId: "p15",
    gradeLevelId: "g14",
    gradeName: "12th Grade",
    gradeShortCode: "12",
    description: "Apply to universities with strong psychology/neuroscience programs. Take AP exams in Psychology, Biology, and Statistics. Write college essays about your passion for understanding the human mind and your experiences helping others. Research combined B.A./Ph.D. or honors programs that accelerate the path to clinical practice.",
    subjects: ["AP Psychology (Exam)", "AP Biology (Exam)", "AP Statistics (Exam)", "AP English (College Essays)", "Neuroscience Elective"],
    extracurriculars: [
      { name: "National Honor Society — Psychology/Mental Health Focus", url: "https://www.nhs.us/", description: "Lead mental health awareness initiatives, peer tutoring, and community service projects." },
      { name: "Capstone Research Project", url: "", description: "Complete a senior capstone research project on a psychology topic — present findings to the school or community." },
    ],
    supplemental: [
      { name: "APA — Graduate Study in Psychology", url: "https://www.apa.org/education-career/grad/", type: "article" },
      { name: "The Psychologist's Companion (APA Style Guide)", url: "", type: "book" },
    ],
  },
  {
    id: "rs643",
    professionId: "p15",
    gradeLevelId: "g15",
    gradeName: "Undergraduate",
    gradeShortCode: "ugrad",
    description: "Major in Psychology, Neuroscience, or a related field. Complete core courses: research methods, statistics, abnormal psychology, developmental psychology, cognitive psychology, social psychology, and biological psychology. Get involved in a research lab — this is essential for Ph.D. applications. Gain clinical or counseling experience through volunteering.",
    subjects: ["Research Methods & Statistics", "Abnormal Psychology", "Developmental Psychology", "Cognitive Neuroscience", "Social Psychology"],
    extracurriculars: [
      { name: "Psi Chi — International Honor Society in Psychology", url: "https://www.psichi.org/", description: "Psychology honor society — research grants, conference presentations, and graduate school preparation." },
      { name: "Undergraduate Research Assistant in a Psychology Lab", url: "", description: "Work in a professor's lab — the single most important experience for Ph.D. applications in psychology." },
    ],
    supplemental: [
      { name: "GRE Psychology Subject Test Prep", url: "https://www.ets.org/gre/", type: "program" },
      { name: "APA Style Guide (7th Edition)", url: "https://apastyle.apa.org/", type: "book" },
    ],
  },
  {
    id: "rs644",
    professionId: "p15",
    gradeLevelId: "g16",
    gradeName: "Graduate",
    gradeShortCode: "grad",
    description: "Pursue a Ph.D. or Psy.D. in Clinical, Counseling, School, or Research Psychology. Ph.D. programs (5-7 years) emphasize research and clinical training; Psy.D. programs (4-6 years) emphasize clinical practice. Complete a year-long predoctoral internship (APPIC match) and postdoctoral supervised hours for licensure. Pass the EPPP national licensing exam.",
    subjects: ["Advanced Psychopathology", "Psychological Assessment", "Evidence-Based Interventions", "Clinical Practicum", "Dissertation Research"],
    extracurriculars: [
      { name: "APA Student Membership (APAGS)", url: "https://www.apa.org/apags/", description: "American Psychological Association of Graduate Students — professional development, advocacy, and networking." },
      { name: "APPIC Internship Match", url: "https://www.appic.org/", description: "The national internship matching process required for clinical psychology doctoral students." },
    ],
    supplemental: [
      { name: "DSM-5-TR (Diagnostic and Statistical Manual)", url: "", type: "book" },
      { name: "EPPP Exam Prep (PsychPrep / AATBS)", url: "https://www.asppb.net/", type: "program" },
    ],
  },
  {
    id: "rs645",
    professionId: "p15",
    gradeLevelId: "g17",
    gradeName: "PhD / Doctoral",
    gradeShortCode: "phd",
    description: "Complete the Ph.D./Psy.D., predoctoral internship, and postdoctoral fellowship. Obtain state licensure as a psychologist. Specialization options through postdoctoral training: neuropsychology, forensic psychology, health psychology, child/adolescent, or geropsychology. Board certification (ABPP) recognizes advanced expertise. Psychologists can work in private practice, hospitals, schools, research, or academia.",
    subjects: ["Postdoctoral Specialization", "Licensing Exam Preparation", "Board Certification (ABPP)", "Supervision & Teaching", "Continuing Education"],
    extracurriculars: [
      { name: "American Board of Professional Psychology (ABPP)", url: "https://www.abpp.org/", description: "Board certification in 15 psychology specialties — the highest credential recognizing advanced competence." },
      { name: "APA Annual Convention", url: "https://convention.apa.org/", description: "The largest gathering of psychologists worldwide — present research, attend workshops, and network." },
    ],
    supplemental: [
      { name: "American Psychologist (APA Journal)", url: "https://www.apa.org/pubs/journals/amp", type: "article" },
      { name: "Clinical Psychology: Science, Practice, and Diversity — Andrew Pomerantz", url: "", type: "book" },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // p16 — Electrician (all 17 grades)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "rs646",
    professionId: "p16",
    gradeLevelId: "g1",
    gradeName: "Pre-K",
    gradeShortCode: "prek",
    description: "Electricity is everywhere — lights, toys, and screens! At this age, children are fascinated by things that light up, move, and make sounds. Encourage curiosity about how things work. Play with battery-powered toys and talk about 'on' and 'off.' Safety around electricity starts here: never touch outlets or cords with wet hands.",
    subjects: ["Curiosity About How Things Work", "On/Off & Cause/Effect", "Colors (Wire Colors)", "Safety Rules"],
    extracurriculars: [
      { name: "Snap Circuits Jr. (with parent supervision)", url: "https://www.elenco.com/snap-circuits/", description: "Safe, snap-together electronic circuits for young children — build working light, fan, and sound projects." },
      { name: "Children's Museums — Electricity Exhibits", url: "https://www.childrensmuseums.org/", description: "Hands-on exhibits with circuits, magnets, and lights that introduce electrical concepts through play." },
    ],
    supplemental: [
      { name: "The Boy Who Harnessed the Wind (Picture Book) — William Kamkwamba", url: "", type: "book" },
      { name: "Oscar and the Bird: A Book About Electricity by Geoff Waring", url: "", type: "book" },
    ],
  },
  {
    id: "rs647",
    professionId: "p16",
    gradeLevelId: "g2",
    gradeName: "Kindergarten",
    gradeShortCode: "k",
    description: "Build curiosity about electricity and how things work. Learn what needs electricity to run vs. what doesn't. Practice fine motor skills through building and connecting — electricians need excellent hand dexterity. Safety first: understand that electricity can be dangerous and should only be handled by trained adults.",
    subjects: ["Counting & Sorting", "Fine Motor Skills", "Early Science (Energy)", "Safety Awareness"],
    extracurriculars: [
      { name: "LEGO Powered Up / Motorized Sets", url: "https://www.lego.com/en-us/themes/powered-up", description: "Build motorized LEGO creations — first hands-on experience with motors, gears, and simple machines." },
      { name: "Home Depot Kids Workshops (with parent)", url: "https://www.homedepot.com/c/kids", description: "Free building workshops for kids — use tools, follow instructions, and build real projects." },
    ],
    supplemental: [
      { name: "When Charlie McButton Lost Power by Suzanne Collins", url: "", type: "book" },
      { name: "Switch On, Switch Off (Let's-Read-and-Find-Out Science)", url: "", type: "book" },
    ],
  },
  {
    id: "rs648",
    professionId: "p16",
    gradeLevelId: "g3",
    gradeName: "1st Grade",
    gradeShortCode: "1",
    description: "Build reading and math skills — electricians read blueprints, codes, and manuals, and use math for measurements and calculations. Learn about circuits: a circle that electricity travels through. Build simple circuits with batteries, wires, and bulbs (with adult help). Practice using basic tools safely.",
    subjects: ["Reading & Writing", "Math (Measurement & Addition)", "Science (Simple Circuits)", "Fine Motor Skills (Tools)"],
    extracurriculars: [
      { name: "Snap Circuits Beginner", url: "https://www.elenco.com/snap-circuits/", description: "Build 20+ electronic projects with safe snap-together circuits — lights, fans, alarms, and more." },
      { name: "DIY.org — Engineering Challenges", url: "https://diy.org/", description: "Online community where kids complete hands-on engineering and building challenges." },
    ],
    supplemental: [
      { name: "The Magic School Bus and the Electric Field Trip", url: "", type: "book" },
      { name: "BrainPOP Jr.: Energy", url: "https://jr.brainpop.com/science/energy/", type: "video" },
    ],
  },
  {
    id: "rs649",
    professionId: "p16",
    gradeLevelId: "g4",
    gradeName: "2nd Grade",
    gradeShortCode: "2",
    description: "Deepen understanding of electricity: conductors, insulators, and how switches work. Build more complex circuits. Practice measuring — electricians measure wire length, conduit runs, and distances constantly. Learn about electrical safety equipment: rubber gloves, insulated tools, and circuit testers. Start a journal of electrical observations around your home.",
    subjects: ["Reading Comprehension", "Math (Measurement & Geometry)", "Science (Electricity & Magnetism)", "Art (Drawing Circuits & Plans)"],
    extracurriculars: [
      { name: "Science Buddies — Electricity Projects", url: "https://www.sciencebuddies.org/", description: "Free hands-on electricity projects — build circuits, electromagnets, and motors." },
      { name: "KiwiCo / Tinker Crate — Electricity & Circuits", url: "https://www.kiwico.com/", description: "Monthly STEM crates with hands-on electrical, engineering, and science projects." },
    ],
    supplemental: [
      { name: "National Geographic Kids: Electricity", url: "https://kids.nationalgeographic.com/science/article/electricity", type: "article" },
      { name: "DK Findout! Energy", url: "https://www.dkfindout.com/us/science/energy/", type: "article" },
    ],
  },
  {
    id: "rs650",
    professionId: "p16",
    gradeLevelId: "g5",
    gradeName: "3rd Grade",
    gradeShortCode: "3",
    description: "Math skills expand — multiplication, division, and fractions are used for calculating electrical loads, voltages, and wire sizes. Learn about renewable energy: solar panels, wind turbines, and batteries. Electricians are on the front lines of the green energy revolution. Build a lemon battery or solar-powered device.",
    subjects: ["Math (Fractions & Multiplication)", "Science (Energy & Electricity)", "Reading (Technical Instructions)", "Technology (Basic Circuits)"],
    extracurriculars: [
      { name: "4-H Electricity & Energy Programs", url: "https://4-h.org/programs/stem/", description: "Youth programs exploring electricity, renewable energy, and electrical safety through hands-on projects." },
      { name: "Science Fair — Renewable Energy Project", url: "", description: "Enter a science fair with a project about solar power, wind energy, or electrical circuits." },
    ],
    supplemental: [
      { name: "DK Electricity (Eyewitness)", url: "", type: "book" },
      { name: "Mystery Science: Energizing Everything", url: "https://mysteryscience.com/", type: "course" },
    ],
  },
  {
    id: "rs651",
    professionId: "p16",
    gradeLevelId: "g6",
    gradeName: "4th Grade",
    gradeShortCode: "4",
    description: "Expand knowledge of electricity, circuits, and energy. Learn the difference between series and parallel circuits — electricians work with both every day. Study how electrical power gets from the power plant to your home. Practice following diagrams and instructions carefully — precision matters in electrical work.",
    subjects: ["English (Technical Reading)", "Math (Proportions & Conversion)", "Science (Energy Systems)", "Art (Diagram Reading)"],
    extracurriculars: [
      { name: "Snap Circuits Pro / Advanced", url: "https://www.elenco.com/snap-circuits/", description: "500+ projects — build radios, digital displays, and complex circuits that teach real electrical concepts." },
      { name: "Maker Camp / Community Makerspace", url: "https://makercamp.com/", description: "Join a makerspace and use real tools — soldering irons, multimeters, and electronic components." },
    ],
    supplemental: [
      { name: "Make: Electronics by Charles Platt", url: "", type: "book" },
      { name: "Khan Academy: Electrical Engineering", url: "https://www.khanacademy.org/science/electrical-engineering", type: "course" },
    ],
  },
  {
    id: "rs652",
    professionId: "p16",
    gradeLevelId: "g7",
    gradeName: "5th Grade",
    gradeShortCode: "5",
    description: "Build strong math and science foundations. Electricians use algebra-based calculations daily: Ohm's Law (V=IR) and power calculations (P=VI). Learn to use a multimeter to measure voltage, current, and resistance. Build more advanced electronics projects. Consider joining a robotics club — electrical and wiring skills are essential.",
    subjects: ["Math (Pre-Algebra & Formulas)", "General Science (Physics of Electricity)", "Computer Skills (Basic)", "Art (Design & Planning)"],
    extracurriculars: [
      { name: "FIRST LEGO League", url: "https://www.firstlegoleague.org/", description: "Build and program robots — learn wiring, sensors, and motor control with electrical components." },
      { name: "LittleBits / Electronic Building Kits", url: "https://www.littlebits.com/", description: "Magnetic electronic building blocks that snap together — create inventions with sensors, motors, and lights." },
    ],
    supplemental: [
      { name: "Ohm's Law Workbook (online resources)", url: "", type: "book" },
      { name: "Crash Course Kids: Engineering", url: "https://www.youtube.com/playlist?list=PLhz12vamHOnZ4ZDC0dS6C9HRN5Qrm0jHO", type: "video" },
    ],
  },
  {
    id: "rs653",
    professionId: "p16",
    gradeLevelId: "g8",
    gradeName: "6th Grade",
    gradeShortCode: "6",
    description: "Take pre-algebra and science seriously — electricians use math every day. Learn about home electrical systems: breaker panels, outlets, switches, and wiring. Study electrical safety codes and why they exist. The skilled trades are high-demand careers with excellent pay — electricians earn great money without college debt.",
    subjects: ["Pre-Algebra", "Physical Science", "Technical Education (if available)", "English (Reading Diagrams & Manuals)"],
    extracurriculars: [
      { name: "FIRST Tech Challenge (FTC)", url: "https://www.firstinspires.org/robotics/ftc", description: "Middle school robotics — build and wire competition robots with motors, sensors, and controllers." },
      { name: "SkillsUSA (Middle School)", url: "https://www.skillsusa.org/", description: "Career and technical student organization — explore electrical, construction, and engineering technology competitions." },
    ],
    supplemental: [
      { name: "The Manga Guide to Electricity", url: "", type: "book" },
      { name: "YouTube: This Old House — Electrical Basics", url: "https://www.youtube.com/@thisoldhouse", type: "video" },
    ],
  },
  {
    id: "rs654",
    professionId: "p16",
    gradeLevelId: "g9",
    gradeName: "7th Grade",
    gradeShortCode: "7",
    description: "Take algebra and any technical education classes. Learn about AC vs. DC power — the two types of electrical current. Build circuits on a breadboard and practice soldering (with supervision). Research electrical apprenticeship programs: most electricians learn through 4-5 year paid apprenticeships, not college. Start building hand-tool skills.",
    subjects: ["Algebra I", "Physical Science / Physics", "Technical Education / Shop Class", "English (Technical Writing)", "Math (Applied Problems)"],
    extracurriculars: [
      { name: "Maker Faire / Maker Movement", url: "https://makerfaire.com/", description: "Attend a Maker Faire and see electrical projects, 3D printing, and hands-on making — get inspired." },
      { name: "Arduino Starter Kit", url: "https://www.arduino.cc/", description: "Learn to program microcontrollers and build interactive electronic projects — foundational for modern electrical work." },
    ],
    supplemental: [
      { name: "Electronics for Kids by Oyvind Nydal Dahl", url: "", type: "book" },
      { name: "Raspberry Pi Foundation — Projects", url: "https://projects.raspberrypi.org/", type: "program" },
    ],
  },
  {
    id: "rs655",
    professionId: "p16",
    gradeLevelId: "g10",
    gradeName: "8th Grade",
    gradeShortCode: "8",
    description: "Take geometry and any technical/vocational courses. Math is essential — electricians calculate conduit bends, wire fill, voltage drop, and load balancing. Learn about the National Electrical Code (NEC). Research the apprenticeship pathway: contact local IBEW (International Brotherhood of Electrical Workers) chapters about their programs.",
    subjects: ["Geometry", "Physical Science", "Career & Technical Education (CTE)", "Applied Math", "English (Technical Communication)"],
    extracurriculars: [
      { name: "SkillsUSA — Electrical Construction Wiring", url: "https://www.skillsusa.org/", description: "Compete in electrical wiring, residential systems, and related technical skills events at the middle/high school level." },
      { name: "VEX Robotics", url: "https://www.vexrobotics.com/", description: "Design and wire competition robots — electrical, sensor, and motor control systems." },
    ],
    supplemental: [
      { name: "Ugly's Electrical References (Student Edition)", url: "", type: "book" },
      { name: "IBEW — Become an Electrician", url: "https://www.ibew.org/", type: "article" },
    ],
  },
  {
    id: "rs656",
    professionId: "p16",
    gradeLevelId: "g11",
    gradeName: "9th Grade",
    gradeShortCode: "9",
    description: "Take algebra/physics and any CTE electrical or construction courses. The high school years are when many future electricians get their first hands-on experience. Learn to use electrical tools: wire strippers, voltage testers, conduit benders. Visit a construction site or electrical contractor to see the trade in action. Electricians are problem-solvers on their feet every day.",
    subjects: ["Algebra I / Geometry", "Physics (Electricity & Magnetism)", "CTE: Electrical Trades", "Blueprint Reading", "PE / Physical Fitness"],
    extracurriculars: [
      { name: "SkillsUSA High School Chapter", url: "https://www.skillsusa.org/", description: "Join SkillsUSA — compete in electrical construction wiring, residential wiring, and technical math." },
      { name: "FIRST Robotics Competition (FRC) — Electrical Team", url: "https://www.firstinspires.org/robotics/frc", description: "Join the electrical subteam — wire the robot, manage power distribution, and troubleshoot electrical systems." },
    ],
    supplemental: [
      { name: "NEC Code Book (NFPA 70) — Student Introduction", url: "https://www.nfpa.org/", type: "book" },
      { name: "Electrician U (YouTube)", url: "https://www.youtube.com/@ElectricianU", type: "video" },
    ],
  },
  {
    id: "rs657",
    professionId: "p16",
    gradeLevelId: "g12",
    gradeName: "10th Grade",
    gradeShortCode: "10",
    description: "Take physics and advanced math. Electricity is applied physics. Continue CTE electrical courses if available. Consider a summer job as an electrical helper or construction laborer. Research apprenticeship programs: union (IBEW/NECA) vs. non-union (ABC/IEACI). Most apprenticeships require a high school diploma, algebra proficiency, and a drug test.",
    subjects: ["Physics", "Algebra II", "CTE: Advanced Electrical", "Drafting / Blueprint Reading", "English (Technical Writing)"],
    extracurriculars: [
      { name: "Summer Electrical Helper / Construction Job", url: "", description: "Work as a helper on a construction site or with an electrical contractor — real-world experience and great pay." },
      { name: "NCCER Electrical Level 1 (Student)", url: "https://www.nccer.org/", description: "National Center for Construction Education and Research — industry-recognized electrical training credentials." },
    ],
    supplemental: [
      { name: "Residential Electrical Wiring (textbook)", url: "", type: "book" },
      { name: "Mike Holt Enterprises — Electrical Training", url: "https://www.mikeholt.com/", type: "course" },
    ],
  },
  {
    id: "rs658",
    professionId: "p16",
    gradeLevelId: "g13",
    gradeName: "11th Grade",
    gradeShortCode: "11",
    description: "This is the year to seriously plan your electrical career path. Research local apprenticeship programs and their application timelines. Many unions accept applications only during specific windows. Take any remaining CTE courses. Consider dual-enrollment at a technical college for electrical technology. Prepare for the IBEW aptitude test (algebra and reading comprehension).",
    subjects: ["CTE: Electrical Technology (Advanced)", "Pre-Calculus / Trigonometry", "Physics", "English (Application & Resume Writing)", "Construction / Blueprint Reading"],
    extracurriculars: [
      { name: "IBEW Apprenticeship Application", url: "https://www.ibew.org/", description: "Research and prepare for IBEW apprenticeship applications — the most respected pathway to becoming a journeyman electrician." },
      { name: "Job Shadow an Electrician", url: "", description: "Spend a day (or more) shadowing a licensed electrician — see the real work, ask questions, and confirm your career choice." },
    ],
    supplemental: [
      { name: "IBEW Aptitude Test Prep", url: "https://www.electricprep.com/", type: "program" },
      { name: "Ohm's Law & Electrical Math Workbook", url: "", type: "book" },
    ],
  },
  {
    id: "rs659",
    professionId: "p16",
    gradeLevelId: "g14",
    gradeName: "12th Grade",
    gradeShortCode: "12",
    description: "Apply to electrical apprenticeship programs (IBEW, IEC, or ABC). The typical path: 4-5 year apprenticeship combining paid on-the-job training (8,000 hours) with classroom instruction (500-1,000 hours). Also consider electrical technology programs at community colleges as an alternative entry path. Graduate high school — a diploma is required for apprenticeship.",
    subjects: ["CTE: Electrical Capstone", "Applied Math / Trigonometry", "Physics (or AP Physics)", "Economics (Running Your Own Business)", "English (Communication Skills)"],
    extracurriculars: [
      { name: "Part-Time Electrical Apprentice / Helper", url: "", description: "Start working in the trade — many contractors hire high school seniors for after-school and weekend electrical work." },
      { name: "OSHA 10-Hour Construction Safety", url: "https://www.osha.gov/", description: "Earn your OSHA 10 safety certification — required for most construction jobs and apprenticeship programs." },
    ],
    supplemental: [
      { name: "Mike Holt's Illustrated Guide to Electrical Exam Preparation", url: "", type: "book" },
      { name: "NEC 2023 Code Book (Student Edition)", url: "https://www.nfpa.org/", type: "book" },
    ],
  },
  {
    id: "rs660",
    professionId: "p16",
    gradeLevelId: "g15",
    gradeName: "Undergraduate",
    gradeShortCode: "ugrad",
    description: "Complete a 4-5 year electrical apprenticeship (the 'earn while you learn' model). Apprentices earn a living wage that increases with experience while completing 8,000 hours of on-the-job training and 500-1,000 hours of classroom instruction. Alternatively, earn an A.S. in Electrical Technology at a community college, then enter an apprenticeship with advanced standing.",
    subjects: ["Electrical Theory & Code (NEC)", "Residential & Commercial Wiring", "Motor Controls & PLCs", "Blueprint Reading & Estimating", "Safety & OSHA Standards"],
    extracurriculars: [
      { name: "IBEW Apprenticeship Program", url: "https://www.ibew.org/", description: "Joint Apprenticeship and Training Committee (JATC) programs — earn $30-50K+ as an apprentice with full benefits." },
      { name: "Independent Electrical Contractors (IEC) Apprenticeship", url: "https://www.ieci.org/", description: "Non-union apprenticeship pathway with similar training standards and career outcomes." },
    ],
    supplemental: [
      { name: "Mike Holt's Electrical Exam Preparation", url: "https://www.mikeholt.com/", type: "program" },
      { name: "Electrician's Troubleshooting and Testing Pocket Guide", url: "", type: "book" },
    ],
  },
  {
    id: "rs661",
    professionId: "p16",
    gradeLevelId: "g16",
    gradeName: "Graduate",
    gradeShortCode: "grad",
    description: "After completing apprenticeship, pass the journeyman electrician exam for state licensure. Journeymen can work independently and supervise apprentices. After 2+ years as a journeyman, qualify for the master electrician exam. Master electricians can pull permits, own contracting businesses, and design electrical systems. Median pay: $60K-100K+ with excellent benefits.",
    subjects: ["Journeyman Exam Preparation", "Advanced NEC Code", "Electrical System Design", "Project Management", "Business / Contracting Basics"],
    extracurriculars: [
      { name: "IBEW Journeyman Upgrade Training", url: "https://www.ibew.org/", description: "Continuing education through IBEW — stay current with code changes, new technologies, and specialized skills." },
      { name: "NECA (National Electrical Contractors Association)", url: "https://www.necanet.org/", description: "Professional organization for electrical contractors — business resources, networking, and industry advocacy." },
    ],
    supplemental: [
      { name: "Master Electrician Exam Prep (Mike Holt)", url: "https://www.mikeholt.com/", type: "program" },
      { name: "NEC Handbook (Comprehensive)", url: "https://www.nfpa.org/", type: "book" },
    ],
  },
  {
    id: "rs662",
    professionId: "p16",
    gradeLevelId: "g17",
    gradeName: "PhD / Doctoral",
    gradeShortCode: "phd",
    description: "In the electrical trade, 'doctorate level' means becoming a Master Electrician and/or Electrical Contractor — owning your own business, designing complex electrical systems, or specializing in areas like industrial controls, renewable energy, or fire alarm systems. Some electricians pursue a B.S. in Electrical Engineering to transition into design roles. Others become electrical inspectors or code enforcement officials.",
    subjects: ["Master Electrician License", "Electrical Contracting Business", "Advanced System Design", "Code Enforcement & Inspection", "Mentoring & Training Apprentices"],
    extracurriculars: [
      { name: "National Electrical Contractors Association (NECA)", url: "https://www.necanet.org/", description: "Advocacy, education, and business resources for electrical contractors — the voice of the electrical construction industry." },
      { name: "International Association of Electrical Inspectors (IAEI)", url: "https://www.iaei.org/", description: "Professional organization for electrical inspectors — code education, certification, and industry standards." },
    ],
    supplemental: [
      { name: "EC&M Magazine (Electrical Construction & Maintenance)", url: "https://www.ecmweb.com/", type: "article" },
      { name: "NFPA 70E — Electrical Safety in the Workplace", url: "https://www.nfpa.org/", type: "book" },
    ],
  },
];
