/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpotlightsRouteImport } from './routes/spotlights'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as ProfessionsRouteImport } from './routes/professions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessionsIndexRouteImport } from './routes/professions.index'
import { Route as ProfessionsSlugRouteImport } from './routes/professions/$slug'
import { Route as ProfessionsSlugRoadmapRouteImport } from './routes/professions/$slug/roadmap'

const SpotlightsRoute = SpotlightsRouteImport.update({
  id: '/spotlights',
  path: '/spotlights',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionsRoute = ProfessionsRouteImport.update({
  id: '/professions',
  path: '/professions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionsIndexRoute = ProfessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfessionsRoute,
} as any)
const ProfessionsSlugRoute = ProfessionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProfessionsRoute,
} as any)
const ProfessionsSlugRoadmapRoute = ProfessionsSlugRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => ProfessionsSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/professions': typeof ProfessionsRouteWithChildren
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/spotlights': typeof SpotlightsRoute
  '/professions/$slug': typeof ProfessionsSlugRouteWithChildren
  '/professions/': typeof ProfessionsIndexRoute
  '/professions/$slug/roadmap': typeof ProfessionsSlugRoadmapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/spotlights': typeof SpotlightsRoute
  '/professions/$slug': typeof ProfessionsSlugRouteWithChildren
  '/professions': typeof ProfessionsIndexRoute
  '/professions/$slug/roadmap': typeof ProfessionsSlugRoadmapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/professions': typeof ProfessionsRouteWithChildren
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/spotlights': typeof SpotlightsRoute
  '/professions/$slug': typeof ProfessionsSlugRouteWithChildren
  '/professions/': typeof ProfessionsIndexRoute
  '/professions/$slug/roadmap': typeof ProfessionsSlugRoadmapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/professions'
    | '/schools'
    | '/signup'
    | '/spotlights'
    | '/professions/$slug'
    | '/professions/'
    | '/professions/$slug/roadmap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/schools'
    | '/signup'
    | '/spotlights'
    | '/professions/$slug'
    | '/professions'
    | '/professions/$slug/roadmap'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/professions'
    | '/schools'
    | '/signup'
    | '/spotlights'
    | '/professions/$slug'
    | '/professions/'
    | '/professions/$slug/roadmap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfessionsRoute: typeof ProfessionsRouteWithChildren
  SchoolsRoute: typeof SchoolsRoute
  SignupRoute: typeof SignupRoute
  SpotlightsRoute: typeof SpotlightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spotlights': {
      id: '/spotlights'
      path: '/spotlights'
      fullPath: '/spotlights'
      preLoaderRoute: typeof SpotlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professions': {
      id: '/professions'
      path: '/professions'
      fullPath: '/professions'
      preLoaderRoute: typeof ProfessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professions/': {
      id: '/professions/'
      path: '/'
      fullPath: '/professions/'
      preLoaderRoute: typeof ProfessionsIndexRouteImport
      parentRoute: typeof ProfessionsRoute
    }
    '/professions/$slug': {
      id: '/professions/$slug'
      path: '/$slug'
      fullPath: '/professions/$slug'
      preLoaderRoute: typeof ProfessionsSlugRouteImport
      parentRoute: typeof ProfessionsRoute
    }
    '/professions/$slug/roadmap': {
      id: '/professions/$slug/roadmap'
      path: '/roadmap'
      fullPath: '/professions/$slug/roadmap'
      preLoaderRoute: typeof ProfessionsSlugRoadmapRouteImport
      parentRoute: typeof ProfessionsSlugRoute
    }
  }
}

interface ProfessionsSlugRouteChildren {
  ProfessionsSlugRoadmapRoute: typeof ProfessionsSlugRoadmapRoute
}

const ProfessionsSlugRouteChildren: ProfessionsSlugRouteChildren = {
  ProfessionsSlugRoadmapRoute: ProfessionsSlugRoadmapRoute,
}

const ProfessionsSlugRouteWithChildren = ProfessionsSlugRoute._addFileChildren(
  ProfessionsSlugRouteChildren,
)

interface ProfessionsRouteChildren {
  ProfessionsSlugRoute: typeof ProfessionsSlugRouteWithChildren
  ProfessionsIndexRoute: typeof ProfessionsIndexRoute
}

const ProfessionsRouteChildren: ProfessionsRouteChildren = {
  ProfessionsSlugRoute: ProfessionsSlugRouteWithChildren,
  ProfessionsIndexRoute: ProfessionsIndexRoute,
}

const ProfessionsRouteWithChildren = ProfessionsRoute._addFileChildren(
  ProfessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfessionsRoute: ProfessionsRouteWithChildren,
  SchoolsRoute: SchoolsRoute,
  SignupRoute: SignupRoute,
  SpotlightsRoute: SpotlightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
