/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorsRouteImport } from './routes/tutors'
import { Route as SpotlightsRouteImport } from './routes/spotlights'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as ProfessionsRouteImport } from './routes/professions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TutorsIndexRouteImport } from './routes/tutors.index'
import { Route as ProfessionsIndexRouteImport } from './routes/professions.index'
import { Route as TutorsAiRouteImport } from './routes/tutors/ai'
import { Route as TutorsTutorIdRouteImport } from './routes/tutors/$tutorId'
import { Route as ProfessionsSlugIndexRouteImport } from './routes/professions/$slug/index'
import { Route as ProfessionsSlugRoadmapRouteImport } from './routes/professions/$slug/roadmap'

const TutorsRoute = TutorsRouteImport.update({
  id: '/tutors',
  path: '/tutors',
  getParentRoute: () => rootRouteImport,
} as any)
const SpotlightsRoute = SpotlightsRouteImport.update({
  id: '/spotlights',
  path: '/spotlights',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionsRoute = ProfessionsRouteImport.update({
  id: '/professions',
  path: '/professions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorsIndexRoute = TutorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TutorsRoute,
} as any)
const ProfessionsIndexRoute = ProfessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfessionsRoute,
} as any)
const TutorsAiRoute = TutorsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => TutorsRoute,
} as any)
const TutorsTutorIdRoute = TutorsTutorIdRouteImport.update({
  id: '/$tutorId',
  path: '/$tutorId',
  getParentRoute: () => TutorsRoute,
} as any)
const ProfessionsSlugIndexRoute = ProfessionsSlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => ProfessionsRoute,
} as any)
const ProfessionsSlugRoadmapRoute = ProfessionsSlugRoadmapRouteImport.update({
  id: '/$slug/roadmap',
  path: '/$slug/roadmap',
  getParentRoute: () => ProfessionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/professions': typeof ProfessionsRouteWithChildren
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/spotlights': typeof SpotlightsRoute
  '/tutors': typeof TutorsRouteWithChildren
  '/tutors/$tutorId': typeof TutorsTutorIdRoute
  '/tutors/ai': typeof TutorsAiRoute
  '/professions/': typeof ProfessionsIndexRoute
  '/tutors/': typeof TutorsIndexRoute
  '/professions/$slug/roadmap': typeof ProfessionsSlugRoadmapRoute
  '/professions/$slug/': typeof ProfessionsSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/spotlights': typeof SpotlightsRoute
  '/tutors/$tutorId': typeof TutorsTutorIdRoute
  '/tutors/ai': typeof TutorsAiRoute
  '/professions': typeof ProfessionsIndexRoute
  '/tutors': typeof TutorsIndexRoute
  '/professions/$slug/roadmap': typeof ProfessionsSlugRoadmapRoute
  '/professions/$slug': typeof ProfessionsSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/professions': typeof ProfessionsRouteWithChildren
  '/schools': typeof SchoolsRoute
  '/signup': typeof SignupRoute
  '/spotlights': typeof SpotlightsRoute
  '/tutors': typeof TutorsRouteWithChildren
  '/tutors/$tutorId': typeof TutorsTutorIdRoute
  '/tutors/ai': typeof TutorsAiRoute
  '/professions/': typeof ProfessionsIndexRoute
  '/tutors/': typeof TutorsIndexRoute
  '/professions/$slug/roadmap': typeof ProfessionsSlugRoadmapRoute
  '/professions/$slug/': typeof ProfessionsSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/professions'
    | '/schools'
    | '/signup'
    | '/spotlights'
    | '/tutors'
    | '/tutors/$tutorId'
    | '/tutors/ai'
    | '/professions/'
    | '/tutors/'
    | '/professions/$slug/roadmap'
    | '/professions/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/schools'
    | '/signup'
    | '/spotlights'
    | '/tutors/$tutorId'
    | '/tutors/ai'
    | '/professions'
    | '/tutors'
    | '/professions/$slug/roadmap'
    | '/professions/$slug'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/professions'
    | '/schools'
    | '/signup'
    | '/spotlights'
    | '/tutors'
    | '/tutors/$tutorId'
    | '/tutors/ai'
    | '/professions/'
    | '/tutors/'
    | '/professions/$slug/roadmap'
    | '/professions/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ProfessionsRoute: typeof ProfessionsRouteWithChildren
  SchoolsRoute: typeof SchoolsRoute
  SignupRoute: typeof SignupRoute
  SpotlightsRoute: typeof SpotlightsRoute
  TutorsRoute: typeof TutorsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutors': {
      id: '/tutors'
      path: '/tutors'
      fullPath: '/tutors'
      preLoaderRoute: typeof TutorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spotlights': {
      id: '/spotlights'
      path: '/spotlights'
      fullPath: '/spotlights'
      preLoaderRoute: typeof SpotlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professions': {
      id: '/professions'
      path: '/professions'
      fullPath: '/professions'
      preLoaderRoute: typeof ProfessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutors/': {
      id: '/tutors/'
      path: '/'
      fullPath: '/tutors/'
      preLoaderRoute: typeof TutorsIndexRouteImport
      parentRoute: typeof TutorsRoute
    }
    '/professions/': {
      id: '/professions/'
      path: '/'
      fullPath: '/professions/'
      preLoaderRoute: typeof ProfessionsIndexRouteImport
      parentRoute: typeof ProfessionsRoute
    }
    '/tutors/ai': {
      id: '/tutors/ai'
      path: '/ai'
      fullPath: '/tutors/ai'
      preLoaderRoute: typeof TutorsAiRouteImport
      parentRoute: typeof TutorsRoute
    }
    '/tutors/$tutorId': {
      id: '/tutors/$tutorId'
      path: '/$tutorId'
      fullPath: '/tutors/$tutorId'
      preLoaderRoute: typeof TutorsTutorIdRouteImport
      parentRoute: typeof TutorsRoute
    }
    '/professions/$slug/': {
      id: '/professions/$slug/'
      path: '/$slug'
      fullPath: '/professions/$slug/'
      preLoaderRoute: typeof ProfessionsSlugIndexRouteImport
      parentRoute: typeof ProfessionsRoute
    }
    '/professions/$slug/roadmap': {
      id: '/professions/$slug/roadmap'
      path: '/$slug/roadmap'
      fullPath: '/professions/$slug/roadmap'
      preLoaderRoute: typeof ProfessionsSlugRoadmapRouteImport
      parentRoute: typeof ProfessionsRoute
    }
  }
}

interface ProfessionsRouteChildren {
  ProfessionsIndexRoute: typeof ProfessionsIndexRoute
  ProfessionsSlugRoadmapRoute: typeof ProfessionsSlugRoadmapRoute
  ProfessionsSlugIndexRoute: typeof ProfessionsSlugIndexRoute
}

const ProfessionsRouteChildren: ProfessionsRouteChildren = {
  ProfessionsIndexRoute: ProfessionsIndexRoute,
  ProfessionsSlugRoadmapRoute: ProfessionsSlugRoadmapRoute,
  ProfessionsSlugIndexRoute: ProfessionsSlugIndexRoute,
}

const ProfessionsRouteWithChildren = ProfessionsRoute._addFileChildren(
  ProfessionsRouteChildren,
)

interface TutorsRouteChildren {
  TutorsTutorIdRoute: typeof TutorsTutorIdRoute
  TutorsAiRoute: typeof TutorsAiRoute
  TutorsIndexRoute: typeof TutorsIndexRoute
}

const TutorsRouteChildren: TutorsRouteChildren = {
  TutorsTutorIdRoute: TutorsTutorIdRoute,
  TutorsAiRoute: TutorsAiRoute,
  TutorsIndexRoute: TutorsIndexRoute,
}

const TutorsRouteWithChildren =
  TutorsRoute._addFileChildren(TutorsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ProfessionsRoute: ProfessionsRouteWithChildren,
  SchoolsRoute: SchoolsRoute,
  SignupRoute: SignupRoute,
  SpotlightsRoute: SpotlightsRoute,
  TutorsRoute: TutorsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
